/* 词库 ③：雅思（IELTS）核心学术词 —— 覆盖 AWL 学术词表 + 雅思高频话题词 */
window.VOCAB_IELTS = [
{w:"analyse",p:"/ˈænəlaɪz/",t:"v.",z:"分析",e:"We need to analyse the data carefully.",ez:"我们需要仔细分析这些数据。"},
{w:"analysis",p:"/əˈnæləsɪs/",t:"n.",z:"分析",e:"The analysis reveals a clear trend.",ez:"分析揭示了一个明显趋势。"},
{w:"approach",p:"/əˈproʊtʃ/",t:"n./v.",z:"方法；接近",e:"A different approach is needed.",ez:"需要一种不同的方法。"},
{w:"assess",p:"/əˈses/",t:"v.",z:"评估",e:"It's hard to assess the impact.",ez:"影响难以评估。"},
{w:"assessment",p:"/əˈsesmənt/",t:"n.",z:"评估，考核",e:"Continuous assessment is used here.",ez:"这里采用持续性考核。"},
{w:"assume",p:"/əˈsuːm/",t:"v.",z:"假设；承担",e:"Let's assume that's true.",ez:"我们假设那是真的。"},
{w:"assumption",p:"/əˈsʌmpʃn/",t:"n.",z:"假设",e:"That assumption may be flawed.",ez:"那个假设可能有漏洞。"},
{w:"authority",p:"/əˈθɔːrəti/",t:"n.",z:"权威；当局",e:"The local authority should act.",ez:"地方当局应该采取行动。"},
{w:"available",p:"/əˈveɪləbl/",t:"adj.",z:"可获得的",e:"Resources are limited but available.",ez:"资源有限但可获得。"},
{w:"benefit",p:"/ˈbenɪfɪt/",t:"n./v.",z:"益处",e:"The benefits outweigh the costs.",ez:"收益大于成本。"},
{w:"concept",p:"/ˈkɑːnsept/",t:"n.",z:"概念",e:"It's a difficult concept to grasp.",ez:"这是个难以理解的概念。"},
{w:"conclude",p:"/kənˈkluːd/",t:"v.",z:"得出结论",e:"The study concluded that exercise helps.",ez:"研究得出结论：运动有帮助。"},
{w:"conduct",p:"/kənˈdʌkt/",t:"v.",z:"实施，进行",e:"They conducted a survey.",ez:"他们开展了一项调查。"},
{w:"consequence",p:"/ˈkɑːnsəkwens/",t:"n.",z:"后果",e:"This could have serious consequences.",ez:"这可能带来严重后果。"},
{w:"considerable",p:"/kənˈsɪdərəbl/",t:"adj.",z:"相当大的",e:"A considerable amount of money.",ez:"相当大一笔钱。"},
{w:"consistent",p:"/kənˈsɪstənt/",t:"adj.",z:"一致的；持续的",e:"The results are consistent.",ez:"结果是一致的。"},
{w:"constitute",p:"/ˈkɑːnstɪtuːt/",t:"v.",z:"构成",e:"Women constitute 60% of the workforce.",ez:"女性占劳动力的60%。"},
{w:"context",p:"/ˈkɑːntekst/",t:"n.",z:"背景，语境",e:"It must be seen in context.",ez:"必须结合背景来看。"},
{w:"contribute",p:"/kənˈtrɪbjuːt/",t:"v.",z:"贡献；促成",e:"Stress contributes to poor health.",ez:"压力会导致健康变差。"},
{w:"data",p:"/ˈdeɪtə/",t:"n.",z:"数据",e:"The data supports this view.",ez:"数据支持这一观点。"},
{w:"decline",p:"/dɪˈklaɪn/",t:"n./v.",z:"下降；婉拒",e:"There was a sharp decline in sales.",ez:"销量急剧下降。"},
{w:"demonstrate",p:"/ˈdemənstreɪt/",t:"v.",z:"证明；演示",e:"The chart demonstrates the growth.",ez:"图表显示了增长。"},
{w:"derive",p:"/dɪˈraɪv/",t:"v.",z:"源自；获得",e:"Energy derived from fossil fuels.",ez:"源自化石燃料的能源。"},
{w:"design",p:"/dɪˈzaɪn/",t:"v./n.",z:"设计",e:"The program was designed for children.",ez:"该项目是为儿童设计的。"},
{w:"despite",p:"/dɪˈspaɪt/",t:"prep.",z:"尽管",e:"Despite the cost, it's popular.",ez:"尽管贵，它还是很受欢迎。"},
{w:"dimension",p:"/daɪˈmenʃn/",t:"n.",z:"维度；方面",e:"The social dimension is important.",ez:"社会层面很重要。"},
{w:"distinct",p:"/dɪˈstɪŋkt/",t:"adj.",z:"明显不同的",e:"Two distinct patterns emerged.",ez:"出现了两种明显不同的模式。"},
{w:"distribution",p:"/ˌdɪstrɪˈbjuːʃn/",t:"n.",z:"分布；分配",e:"The distribution of wealth is uneven.",ez:"财富分配不均。"},
{w:"economic",p:"/ˌiːkəˈnɑːmɪk/",t:"adj.",z:"经济的",e:"Economic growth has slowed.",ez:"经济增长放缓了。"},
{w:"element",p:"/ˈelɪmənt/",t:"n.",z:"要素，元素",e:"Trust is a key element.",ez:"信任是关键要素。"},
{w:"eliminate",p:"/ɪˈlɪmɪneɪt/",t:"v.",z:"消除",e:"We must eliminate poverty.",ez:"我们必须消除贫困。"},
{w:"emerge",p:"/iˈmɜːrdʒ/",t:"v.",z:"出现，兴起",e:"New technologies have emerged.",ez:"新技术已经出现。"},
{w:"emphasise",p:"/ˈemfəsaɪz/",t:"v.",z:"强调",e:"The report emphasises education.",ez:"报告强调教育。"},
{w:"enable",p:"/ɪˈneɪbl/",t:"v.",z:"使能够",e:"This enables faster communication.",ez:"这使得沟通更快。"},
{w:"energy",p:"/ˈenərdʒi/",t:"n.",z:"能源；精力",e:"Renewable energy is essential.",ez:"可再生能源至关重要。"},
{w:"ensure",p:"/ɪnˈʃʊr/",t:"v.",z:"确保",e:"We must ensure equal access.",ez:"我们必须确保机会均等。"},
{w:"environment",p:"/ɪnˈvaɪrənmənt/",t:"n.",z:"环境",e:"Protecting the environment matters.",ez:"保护环境很重要。"},
{w:"establish",p:"/ɪˈstæblɪʃ/",t:"v.",z:"建立，确立",e:"The school was established in 1990.",ez:"这所学校建于1990年。"},
{w:"estimate",p:"/ˈestɪmeɪt/",t:"v./n.",z:"估计",e:"It's estimated that 40% agree.",ez:"据估计有40%的人同意。"},
{w:"evaluate",p:"/ɪˈvæljueɪt/",t:"v.",z:"评价，评估",e:"Students are evaluated annually.",ez:"学生每年接受评估。"},
{w:"evidence",p:"/ˈevɪdəns/",t:"n.",z:"证据",e:"There is little evidence for this.",ez:"这方面证据很少。"},
{w:"exceed",p:"/ɪkˈsiːd/",t:"v.",z:"超过",e:"Costs must not exceed the budget.",ez:"成本不得超过预算。"},
{w:"factor",p:"/ˈfæktər/",t:"n.",z:"因素",e:"Cost is a major factor.",ez:"成本是主要因素。"},
{w:"fluctuate",p:"/ˈflʌktʃueɪt/",t:"v.",z:"波动",e:"Prices fluctuated throughout the year.",ez:"价格全年波动。"},
{w:"fundamental",p:"/ˌfʌndəˈmentl/",t:"adj.",z:"根本的",e:"It's a fundamental issue.",ez:"这是个根本性问题。"},
{w:"generate",p:"/ˈdʒenəreɪt/",t:"v.",z:"产生，生成",e:"Wind farms generate electricity.",ez:"风力发电场发电。"},
{w:"globalisation",p:"/ˌɡloʊbələˈzeɪʃn/",t:"n.",z:"全球化",e:"Globalisation affects local cultures.",ez:"全球化影响本土文化。"},
{w:"guarantee",p:"/ˌɡærənˈtiː/",t:"v./n.",z:"保证",e:"A degree doesn't guarantee a job.",ez:"学位不保证有工作。"},
{w:"identify",p:"/aɪˈdentɪfaɪ/",t:"v.",z:"识别，确定",e:"We identified three main causes.",ez:"我们确定了三个主要原因。"},
{w:"illustrate",p:"/ˈɪləstreɪt/",t:"v.",z:"说明，阐述",e:"Let me illustrate with an example.",ez:"让我举例说明。"},
{w:"impact",p:"/ˈɪmpækt/",t:"n./v.",z:"影响",e:"Tourism impacts the local economy.",ez:"旅游业影响当地经济。"},
{w:"implement",p:"/ˈɪmplɪment/",t:"v.",z:"实施，执行",e:"The policy was implemented last year.",ez:"该政策去年开始实施。"},
{w:"implication",p:"/ˌɪmplɪˈkeɪʃn/",t:"n.",z:"含义，影响",e:"This has implications for policy.",ez:"这对政策有影响。"},
{w:"indicate",p:"/ˈɪndɪkeɪt/",t:"v.",z:"表明，指出",e:"The graph indicates a rise.",ez:"图表显示上升。"},
{w:"individual",p:"/ˌɪndɪˈvɪdʒuəl/",t:"n./adj.",z:"个人；个体的",e:"Each individual must take responsibility.",ez:"每个人都须承担责任。"},
{w:"inevitable",p:"/ɪnˈevɪtəbl/",t:"adj.",z:"不可避免的",e:"Change is inevitable.",ez:"变化不可避免。"},
{w:"infrastructure",p:"/ˈɪnfrəstrʌktʃər/",t:"n.",z:"基础设施",e:"The infrastructure needs investment.",ez:"基础设施需要投资。"},
{w:"inhabitant",p:"/ɪnˈhæbɪtənt/",t:"n.",z:"居民",e:"The city has two million inhabitants.",ez:"这座城市有两百万居民。"},
{w:"initiative",p:"/ɪˈnɪʃətɪv/",t:"n.",z:"倡议；主动性",e:"A new government initiative.",ez:"一项新的政府倡议。"},
{w:"invest",p:"/ɪnˈvest/",t:"v.",z:"投资",e:"We should invest in education.",ez:"我们应该投资教育。"},
{w:"issue",p:"/ˈɪʃuː/",t:"n.",z:"议题，问题",e:"Climate change is a pressing issue.",ez:"气候变化是紧迫议题。"},
{w:"labour",p:"/ˈleɪbər/",t:"n.",z:"劳动力",e:"The labour market is changing.",ez:"劳动力市场在变化。"},
{w:"legislation",p:"/ˌledʒɪsˈleɪʃn/",t:"n.",z:"法规",e:"New legislation was introduced.",ez:"新法规被引入。"},
{w:"maintain",p:"/meɪnˈteɪn/",t:"v.",z:"维持；主张",e:"It's hard to maintain a balance.",ez:"维持平衡很难。"},
{w:"majority",p:"/məˈdʒɔːrəti/",t:"n.",z:"大多数",e:"The majority supported the plan.",ez:"大多数人支持该计划。"},
{w:"methodology",p:"/ˌmeθəˈdɑːlədʒi/",t:"n.",z:"方法论",e:"The methodology was criticised.",ez:"该方法论受到了批评。"},
{w:"migration",p:"/maɪˈɡreɪʃn/",t:"n.",z:"迁移",e:"Rural to urban migration is rising.",ez:"从农村到城市的迁移在增加。"},
{w:"minimum",p:"/ˈmɪnɪməm/",t:"n./adj.",z:"最低限度",e:"A minimum wage was introduced.",ez:"引入了最低工资。"},
{w:"monitor",p:"/ˈmɑːnɪtər/",t:"v./n.",z:"监测",e:"We monitor progress closely.",ez:"我们密切监测进展。"},
{w:"motivate",p:"/ˈmoʊtɪveɪt/",t:"v.",z:"激励",e:"Rewards motivate employees.",ez:"奖励能激励员工。"},
{w:"obtain",p:"/əbˈteɪn/",t:"v.",z:"获得",e:"Permission must be obtained first.",ez:"必须先获得许可。"},
{w:"obvious",p:"/ˈɑːbviəs/",t:"adj.",z:"明显的",e:"The benefits are obvious.",ez:"好处显而易见。"},
{w:"occupation",p:"/ˌɑːkjuˈpeɪʃn/",t:"n.",z:"职业",e:"Please state your occupation.",ez:"请填写您的职业。"},
{w:"participate",p:"/pɑːrˈtɪsɪpeɪt/",t:"v.",z:"参与",e:"Few students participate actively.",ez:"很少有学生积极参与。"},
{w:"perceive",p:"/pərˈsiːv/",t:"v.",z:"感知，认为",e:"It's perceived as a threat.",ez:"这被视为一种威胁。"},
{w:"phenomenon",p:"/fəˈnɑːmɪnən/",t:"n.",z:"现象",e:"This phenomenon is widespread.",ez:"这一现象很普遍。"},
{w:"policy",p:"/ˈpɑːləsi/",t:"n.",z:"政策",e:"The policy failed to work.",ez:"该政策未能奏效。"},
{w:"potential",p:"/pəˈtenʃl/",t:"adj./n.",z:"潜在的；潜力",e:"Potential risks must be considered.",ez:"必须考虑潜在风险。"},
{w:"poverty",p:"/ˈpɑːvərti/",t:"n.",z:"贫困",e:"Half live below the poverty line.",ez:"一半人生活在贫困线以下。"},
{w:"precise",p:"/prɪˈsaɪs/",t:"adj.",z:"精确的",e:"We need precise figures.",ez:"我们需要精确的数字。"},
{w:"previous",p:"/ˈpriːviəs/",t:"adj.",z:"先前的",e:"Previous studies disagree.",ez:"先前的研究结论不同。"},
{w:"primary",p:"/ˈpraɪmeri/",t:"adj.",z:"主要的；初级的",e:"The primary cause is pollution.",ez:"主要原因是污染。"},
{w:"procedure",p:"/prəˈsiːdʒər/",t:"n.",z:"程序，步骤",e:"Follow the correct procedure.",ez:"遵循正确程序。"},
{w:"process",p:"/ˈprɑːses/",t:"n./v.",z:"过程；加工",e:"Learning is a gradual process.",ez:"学习是个渐进的过程。"},
{w:"promote",p:"/prəˈmoʊt/",t:"v.",z:"促进，推广",e:"It promotes healthy living.",ez:"它促进健康生活。"},
{w:"proportion",p:"/prəˈpɔːrʃn/",t:"n.",z:"比例",e:"A large proportion of students.",ez:"很大比例的学生。"},
{w:"pursue",p:"/pərˈsuː/",t:"v.",z:"追求；从事",e:"She pursued a career in law.",ez:"她从事法律职业。"},
{w:"reduce",p:"/rɪˈduːs/",t:"v.",z:"减少",e:"We must reduce emissions.",ez:"我们必须减少排放。"},
{w:"reform",p:"/rɪˈfɔːrm/",t:"n./v.",z:"改革",e:"Education reform is underway.",ez:"教育改革正在进行。"},
{w:"regard",p:"/rɪˈɡɑːrd/",t:"v./n.",z:"看待；关于",e:"It's regarded as essential.",ez:"它被视为必不可少。"},
{w:"region",p:"/ˈriːdʒən/",t:"n.",z:"地区",e:"The region is prone to drought.",ez:"该地区易发生干旱。"},
{w:"regulation",p:"/ˌreɡjuˈleɪʃn/",t:"n.",z:"法规，监管",e:"Stricter regulations are needed.",ez:"需要更严格的监管。"},
{w:"relevant",p:"/ˈreləvənt/",t:"adj.",z:"相关的",e:"That's not relevant here.",ez:"那与此无关。"},
{w:"require",p:"/rɪˈkwaɪər/",t:"v.",z:"需要，要求",e:"The job requires experience.",ez:"这份工作需要经验。"},
{w:"research",p:"/ˈriːsɜːrtʃ/",t:"n./v.",z:"研究",e:"Recent research suggests otherwise.",ez:"近期研究给出了不同结论。"},
{w:"resource",p:"/ˈriːsɔːrs/",t:"n.",z:"资源",e:"Natural resources are depleting.",ez:"自然资源正在枯竭。"},
{w:"respond",p:"/rɪˈspɑːnd/",t:"v.",z:"回应",e:"The government responded quickly.",ez:"政府反应迅速。"},
{w:"restrict",p:"/rɪˈstrɪkt/",t:"v.",z:"限制",e:"They restricted car access.",ez:"他们限制了车辆通行。"},
{w:"reveal",p:"/rɪˈviːl/",t:"v.",z:"揭示",e:"The survey revealed a gap.",ez:"调查揭示了一个差距。"},
{w:"rural",p:"/ˈrʊrəl/",t:"adj.",z:"农村的",e:"Rural areas lack services.",ez:"农村地区缺乏服务。"},
{w:"significant",p:"/sɪɡˈnɪfɪkənt/",t:"adj.",z:"显著的，重要的",e:"A significant increase was recorded.",ez:"记录到了显著增长。"},
{w:"similar",p:"/ˈsɪmələr/",t:"adj.",z:"相似的",e:"Similar trends were observed.",ez:"观察到了相似趋势。"},
{w:"source",p:"/sɔːrs/",t:"n.",z:"来源",e:"Solar is a clean energy source.",ez:"太阳能是清洁能源。"},
{w:"stable",p:"/ˈsteɪbl/",t:"adj.",z:"稳定的",e:"The economy remained stable.",ez:"经济保持稳定。"},
{w:"statistics",p:"/stəˈtɪstɪks/",t:"n.",z:"统计数字",e:"Official statistics tell a different story.",ez:"官方统计数字说法不同。"},
{w:"strategy",p:"/ˈstrætədʒi/",t:"n.",z:"策略",e:"A long-term strategy is needed.",ez:"需要长期战略。"},
{w:"structure",p:"/ˈstrʌktʃər/",t:"n.",z:"结构",e:"The social structure is changing.",ez:"社会结构在变化。"},
{w:"sufficient",p:"/səˈfɪʃnt/",t:"adj.",z:"充足的",e:"There isn't sufficient funding.",ez:"资金不够充足。"},
{w:"survey",p:"/ˈsɜːrveɪ/",t:"n./v.",z:"调查",e:"A survey of 500 people.",ez:"一项500人的调查。"},
{w:"sustainable",p:"/səˈsteɪnəbl/",t:"adj.",z:"可持续的",e:"We need sustainable solutions.",ez:"我们需要可持续的方案。"},
{w:"target",p:"/ˈtɑːrɡɪt/",t:"n./v.",z:"目标；针对",e:"The target was met early.",ez:"目标提前完成。"},
{w:"technique",p:"/tekˈniːk/",t:"n.",z:"技巧，技术",e:"New techniques improved output.",ez:"新技术提高了产量。"},
{w:"tendency",p:"/ˈtendənsi/",t:"n.",z:"趋势，倾向",e:"There's a tendency to overestimate.",ez:"有一种高估的倾向。"},
{w:"theory",p:"/ˈθiːəri/",t:"n.",z:"理论",e:"The theory is widely accepted.",ez:"该理论被广泛接受。"},
{w:"threat",p:"/θret/",t:"n.",z:"威胁",e:"Pollution poses a threat.",ez:"污染构成威胁。"},
{w:"trend",p:"/trend/",t:"n.",z:"趋势",e:"The trend is upward.",ez:"趋势是上升的。"},
{w:"urban",p:"/ˈɜːrbən/",t:"adj.",z:"城市的",e:"Urban living is expensive.",ez:"城市生活很贵。"},
{w:"vary",p:"/ˈveri/",t:"v.",z:"变化，不同",e:"Results vary widely.",ez:"结果差异很大。"},
{w:"welfare",p:"/ˈwelfer/",t:"n.",z:"福利",e:"The welfare system is under strain.",ez:"福利体系承压。"},
{w:"whereas",p:"/ˌwerˈæz/",t:"conj.",z:"然而（用于对比）",e:"The north is rich, whereas the south is poor.",ez:"北方富裕，而南方贫穷。"},
{w:"whereby",p:"/werˈbaɪ/",t:"adv.",z:"借此，由此",e:"A system whereby students choose courses.",ez:"一种学生自主选课的机制。"},
{w:"widespread",p:"/ˈwaɪdspred/",t:"adj.",z:"普遍的",e:"There is widespread support.",ez:"有广泛的支持。"},
/* --- 雅思 Part 1/2/3 口语高频话题词 --- */
{w:"commute",p:"/kəˈmjuːt/",t:"n./v.",z:"通勤",e:"My commute takes an hour.",ez:"我通勤要一小时。"},
{w:"breathtaking",p:"/ˈbreθteɪkɪŋ/",t:"adj.",z:"令人惊叹的",e:"The view was breathtaking.",ez:"景色令人惊叹。"},
{w:"handy",p:"/ˈhændi/",t:"adj.",z:"方便的， handy",e:"That app is really handy.",ez:"那个应用很好用。"},
{w:"leisure",p:"/ˈliːʒər/",t:"n.",z:"闲暇",e:"I have little leisure time.",ez:"我几乎没有闲暇时间。"},
{w:"pastime",p:"/ˈpæstaɪm/",t:"n.",z:"消遣",e:"Reading is my favourite pastime.",ez:"阅读是我最喜欢的消遣。"},
{w:"sedentary",p:"/ˈsednteri/",t:"adj.",z:"久坐的",e:"A sedentary lifestyle is unhealthy.",ez:"久坐的生活方式不健康。"},
{w:"well-being",p:"/wel ˈbiːɪŋ/",t:"n.",z:"幸福感，健康",e:"It improves mental well-being.",ez:"它改善心理健康。"},
{w:"generation gap",p:"/ˌdʒenəˈreɪʃn ɡæp/",t:"n.",z:"代沟",e:"There's a generation gap.",ez:"存在代沟。"},
{w:"cost of living",p:"/kɔːst əv ˈlɪvɪŋ/",t:"n.",z:"生活成本",e:"The cost of living is rising.",ez:"生活成本在上升。"},
{w:"quality of life",p:"/ˈkwɑːləti əv laɪf/",t:"n.",z:"生活质量",e:"It improves quality of life.",ez:"它提高生活质量。"},
{w:"peer pressure",p:"/pɪr ˈpreʃər/",t:"n.",z:"同辈压力",e:"Peer pressure affects teenagers.",ez:"同辈压力影响青少年。"},
{w:"cultural heritage",p:"/ˈkʌltʃərəl ˈherɪtɪdʒ/",t:"n.",z:"文化遗产",e:"We should protect cultural heritage.",ez:"我们应保护文化遗产。"},
{w:"public transport",p:"/ˈpʌblɪk ˈtrænspɔːrt/",t:"n.",z:"公共交通",e:"Public transport is reliable here.",ez:"这里公共交通很可靠。"},
{w:"green space",p:"/ɡriːn speɪs/",t:"n.",z:"绿地",e:"Cities need more green space.",ez:"城市需要更多绿地。"},
{w:"fast food",p:"/fæst fuːd/",t:"n.",z:"快餐",e:"Fast food is convenient.",ez:"快餐很方便。"},
{w:"work-life balance",p:"/wɜːrk laɪf ˈbæləns/",t:"n.",z:"工作生活平衡",e:"Work-life balance matters more now.",ez:"如今工作生活平衡更重要。"},
{w:"distance learning",p:"/ˈdɪstəns ˈlɜːrnɪŋ/",t:"n.",z:"远程学习",e:"Distance learning became common.",ez:"远程学习变得普遍。"},
{w:"vocational",p:"/voʊˈkeɪʃənl/",t:"adj.",z:"职业的",e:"Vocational training is valuable.",ez:"职业培训很有价值。"},
{w:"memorable",p:"/ˈmemərəbl/",t:"adj.",z:"难忘的",e:"It was a memorable experience.",ez:"那是一次难忘的经历。"},
{w:"fascinating",p:"/ˈfæsɪneɪtɪŋ/",t:"adj.",z:"迷人的，极有趣的",e:"I find history fascinating.",ez:"我觉得历史特别迷人。"},
{w:"spacious",p:"/ˈspeɪʃəs/",t:"adj.",z:"宽敞的",e:"The flat is surprisingly spacious.",ez:"这套公寓出奇地宽敞。"},
{w:"convenient",p:"/kənˈviːniənt/",t:"adj.",z:"便利的",e:"It's very convenient for shopping.",ez:"购物非常方便。"},
{w:"affordable housing",p:"/əˈfɔːrdəbl ˈhaʊzɪŋ/",t:"n.",z:"经济适用房",e:"Affordable housing is scarce.",ez:"经济适用房稀缺。"},
{w:"traffic congestion",p:"/ˈtræfɪk kənˈdʒestʃən/",t:"n.",z:"交通拥堵",e:"Traffic congestion is getting worse.",ez:"交通拥堵越来越严重。"},
{w:"carbon footprint",p:"/ˈkɑːrbən ˈfʊtprɪnt/",t:"n.",z:"碳足迹",e:"We should reduce our carbon footprint.",ez:"我们应该减少碳足迹。"},
{w:"renewable",p:"/rɪˈnuːəbl/",t:"adj.",z:"可再生的",e:"Renewable energy is the future.",ez:"可再生能源是未来。"},
{w:"recycle",p:"/ˌriːˈsaɪkl/",t:"v.",z:"回收利用",e:"We recycle paper and plastic.",ez:"我们回收纸和塑料。"},
{w:"obesity",p:"/oʊˈbiːsəti/",t:"n.",z:"肥胖",e:"Obesity rates are climbing.",ez:"肥胖率在上升。"},
{w:"awareness",p:"/əˈwernəs/",t:"n.",z:"意识",e:"It raises public awareness.",ez:"它提高了公众意识。"},
{w:"Advertisement",p:"/ˌædvərˈtaɪzmənt/",t:"n.",z:"广告",e:"Advertisements influence children.",ez:"广告影响儿童。"},
{w:"consumer",p:"/kənˈsuːmər/",t:"n.",z:"消费者",e:"Consumers are more informed now.",ez:"如今消费者更有判断力。"},
{w:"global warming",p:"/ˈɡloʊbl ˈwɔːrmɪŋ/",t:"n.",z:"全球变暖",e:"Global warming is accelerating.",ez:"全球变暖正在加速。"},
{w:"biodiversity",p:"/ˌbaɪoʊdaɪˈvɜːrsəti/",t:"n.",z:"生物多样性",e:"Biodiversity is under threat.",ez:"生物多样性受到威胁。"},
{w:"innovation",p:"/ˌɪnəˈveɪʃn/",t:"n.",z:"创新",e:"Innovation drives growth.",ez:"创新驱动增长。"},
{w:"automation",p:"/ˌɔːtəˈmeɪʃn/",t:"n.",z:"自动化",e:"Automation may replace jobs.",ez:"自动化可能取代工作岗位。"},
{w:"sociable",p:"/ˈsoʊʃəbl/",t:"adj.",z:"好交际的",e:"I'm quite sociable.",ez:"我挺爱社交的。"},
{w:"reliable",p:"/rɪˈlaɪəbl/",t:"adj.",z:"可靠的",e:"He's a reliable friend.",ez:"他是个可靠的朋友。"},
{w:"flexible working",p:"/ˈfleksəbl ˈwɜːrkɪŋ/",t:"n.",z:"弹性工作制",e:"Flexible working improves morale.",ez:"弹性工作制提升士气。"},
{w:"curriculum",p:"/kəˈrɪkjələm/",t:"n.",z:"课程设置",e:"The curriculum is outdated.",ez:"课程设置过时了。"},
{w:"tuition",p:"/tuˈɪʃn/",t:"n.",z:"学费",e:"Tuition fees keep rising.",ez:"学费持续上涨。"},
{w:"dropout",p:"/ˈdrɑːpaʊt/",t:"n.",z:"辍学者",e:"The dropout rate fell.",ez:"辍学率下降了。"},
{w:"literacy",p:"/ˈlɪtərəsi/",t:"n.",z:"读写能力",e:"Adult literacy improved.",ez:"成人识字率提高了。"},
{w:"bilingual",p:"/ˌbaɪˈlɪŋɡwəl/",t:"adj.",z:"双语的",e:"She's bilingual in Spanish.",ez:"她西英双语。"},
{w:"accent",p:"/ˈæksent/",t:"n.",z:"口音",e:"He has a strong accent.",ez:"他口音很重。"},
{w:"fluency",p:"/ˈfluːənsi/",t:"n.",z:"流利度",e:"Fluency comes with practice.",ez:"流利来自练习。"}
];
