/* 词库 ②：美国日常进阶 —— 浸泡式口语高频词，含大量动词短语与习惯表达 */
window.VOCAB_DAILY = [
/* --- 高频口语动词短语 --- */
{w:"come up with",p:"/kʌm ʌp wɪθ/",t:"phr.",z:"想出（主意）",e:"She came up with a great idea.",ez:"她想出了个好主意。"},
{w:"look into",p:"/lʊk ˈɪntuː/",t:"phr.",z:"调查，研究",e:"I'll look into it right away.",ez:"我马上查一下。"},
{w:"put off",p:"/pʊt ɔːf/",t:"phr.",z:"推迟",e:"Don't put it off until tomorrow.",ez:"别拖到明天。"},
{w:"give up",p:"/ɡɪv ʌp/",t:"phr.",z:"放弃",e:"Never give up.",ez:"永不放弃。"},
{w:"bring up",p:"/brɪŋ ʌp/",t:"phr.",z:"提起（话题）；抚养",e:"Don't bring that up again.",ez:"别再提那事了。"},
{w:"point out",p:"/pɔɪnt aʊt/",t:"phr.",z:"指出",e:"He pointed out a mistake.",ez:"他指出了一处错误。"},
{w:"turn out",p:"/tɜːrn aʊt/",t:"phr.",z:"结果是",e:"It turned out great.",ez:"结果非常好。"},
{w:"find out",p:"/faɪnd aʊt/",t:"phr.",z:"查明",e:"Let me find out for you.",ez:"我帮您查一下。"},
{w:"go through",p:"/ɡoʊ θruː/",t:"phr.",z:"经历；仔细检查",e:"I've been going through a lot.",ez:"我最近经历了很多。"},
{w:"deal with",p:"/diːl wɪð/",t:"phr.",z:"处理，应对",e:"I'll deal with it later.",ez:"我待会儿处理。"},
{w:"run into",p:"/rʌn ˈɪntuː/",t:"phr.",z:"偶遇；撞上",e:"I ran into my old teacher.",ez:"我碰到了以前的老师。"},
{w:"look after",p:"/lʊk ˈæftər/",t:"phr.",z:"照顾",e:"Can you look after my dog?",ez:"能帮我照看下狗吗？"},
{w:"get rid of",p:"/ɡet rɪd əv/",t:"phr.",z:"摆脱，扔掉",e:"I need to get rid of these boxes.",ez:"我得把这些箱子处理掉。"},
{w:"keep up with",p:"/kiːp ʌp wɪθ/",t:"phr.",z:"跟上",e:"It's hard to keep up with the news.",ez:"新闻太难跟上了。"},
{w:"make up",p:"/meɪk ʌp/",t:"phr.",z:"编造；和好；化妆",e:"Did you make that up?",ez:"那是你编的吧？"},
{w:"take over",p:"/teɪk ˈoʊvər/",t:"phr.",z:"接管",e:"She took over the project.",ez:"她接管了这个项目。"},
{w:"back up",p:"/bæk ʌp/",t:"phr.",z:"支持；备份",e:"I'll back you up on this.",ez:"这事我支持你。"},
{w:"hold on",p:"/hoʊld ɑːn/",t:"phr.",z:"等一下",e:"Hold on a second.",ez:"稍等一下。"},
{w:"hang on",p:"/hæŋ ɑːn/",t:"phr.",z:"等一等；坚持",e:"Hang on, I'm almost ready.",ez:"等一下，我马上好。"},
{w:"cut it out",p:"/kʌt ɪt aʊt/",t:"phr.",z:"别闹了，住手",e:"Cut it out, guys.",ez:"别闹了，各位。"},
{w:"wrap up",p:"/ræp ʌp/",t:"phr.",z:"收尾，结束",e:"Let's wrap up this meeting.",ez:"我们结束这个会吧。"},
{w:"head out",p:"/hed aʊt/",t:"phr.",z:"出发，动身",e:"I'm heading out now.",ez:"我现在出发。"},
{w:"stop by",p:"/stɑːp baɪ/",t:"phr.",z:"顺道拜访",e:"I'll stop by later.",ez:"我待会儿顺道过来。"},
{w:"sleep in",p:"/sliːp ɪn/",t:"phr.",z:"睡懒觉",e:"I slept in on Saturday.",ez:"我周六睡了个懒觉。"},
{w:"stay up",p:"/steɪ ʌp/",t:"phr.",z:"熬夜",e:"I stayed up till 2 a.m.",ez:"我熬到凌晨两点。"},
{w:"catch on",p:"/kætʃ ɑːn/",t:"phr.",z:"流行起来；理解",e:"It never really caught on.",ez:"它一直没真正流行起来。"},
{w:"carry on",p:"/ˈkæri ɑːn/",t:"phr.",z:"继续",e:"Carry on, please.",ez:"请继续。"},
{w:"wind down",p:"/waɪnd daʊn/",t:"phr.",z:"放松下来",e:"I need time to wind down.",ez:"我需要时间放松一下。"},
{w:"chill out",p:"/tʃɪl aʊt/",t:"phr.",z:"冷静点，放松",e:"Chill out, it's fine.",ez:"冷静点，没事的。"},
{w:"screw up",p:"/skruː ʌp/",t:"phr.",z:"搞砸（口语）",e:"I totally screwed it up.",ez:"我彻底搞砸了。"},
/* --- 俚语与地道表达 --- */
{w:"gonna",p:"/ˈɡʌnə/",t:"phr.",z:"going to 的口语缩读",e:"I'm gonna head out.",ez:"我要走了。"},
{w:"wanna",p:"/ˈwɑːnə/",t:"phr.",z:"want to 的口语缩读",e:"Wanna come with?",ez:"要一起来吗？"},
{w:"gotta",p:"/ˈɡɑːtə/",t:"phr.",z:"got to 的口语缩读，必须",e:"I gotta run.",ez:"我得赶紧走了。"},
{w:"kinda",p:"/ˈkaɪndə/",t:"phr.",z:"有点儿",e:"I'm kinda busy right now.",ez:"我现在有点忙。"},
{w:"sorta",p:"/ˈsɔːrtə/",t:"phr.",z:"算是吧",e:"It's sorta complicated.",ez:"这有点复杂。"},
{w:"outta",p:"/ˈaʊtə/",t:"phr.",z:"out of 的口语缩读",e:"I'm outta here.",ez:"我走了。"},
{w:"lemme",p:"/ˈlemi/",t:"phr.",z:"let me 的口语缩读",e:"Lemme think about it.",ez:"让我想想。"},
{w:"gimme",p:"/ˈɡɪmi/",t:"phr.",z:"give me 的口语缩读",e:"Gimme a second.",ez:"给我一秒钟。"},
{w:"ain't",p:"/eɪnt/",t:"phr.",z:"不是/没有（非正式）",e:"It ain't my problem.",ez:"那不是我的问题。"},
{w:"y'all",p:"/jɔːl/",t:"pron.",z:"你们（美国南方常用）",e:"Are y'all coming?",ez:"你们要来吗？"},
{w:"dude",p:"/duːd/",t:"n.",z:"哥们（称呼，超高频）",e:"Dude, that was insane!",ez:"哥们，那太疯狂了！"},
{w:"cool beans",p:"/kuːl biːnz/",t:"phr.",z:"太好了（轻松表达）",e:"Cool beans, see you then.",ez:"太好了，到时候见。"},
{w:"no way",p:"/noʊ weɪ/",t:"phr.",z:"不会吧！",e:"No way! Are you serious?",ez:"不会吧！你认真的？"},
{w:"for real",p:"/fər riːl/",t:"phr.",z:"真的，认真的",e:"Is he for real?",ez:"他是认真的吗？"},
{w:"give me a break",p:"/ɡɪv miː ə breɪk/",t:"phr.",z:"别闹了；放过我吧",e:"Oh, give me a break.",ez:"拜托，别闹了。"},
{w:"hit the road",p:"/hɪt ðə roʊd/",t:"phr.",z:"上路，出发",e:"Let's hit the road.",ez:"我们出发吧。"},
{w:"call it a day",p:"/kɔːl ɪt ə deɪ/",t:"phr.",z:"今天就到这儿",e:"Let's call it a day.",ez:"今天就到这儿吧。"},
{w:"hang in there",p:"/hæŋ ɪn ðer/",t:"phr.",z:"坚持住",e:"Hang in there, almost done.",ez:"坚持一下，快完了。"},
{w:"piece of cake",p:"/piːs əv keɪk/",t:"phr.",z:"小菜一碟",e:"That test was a piece of cake.",ez:"那场考试小菜一碟。"},
{w:"it's up to you",p:"/ɪts ʌp tuː juː/",t:"phr.",z:"你决定",e:"Where to eat? It's up to you.",ez:"去哪吃？你定。"},
{w:"I'm down",p:"/aɪm daʊn/",t:"phr.",z:"我同意、我来",e:"I'm down for pizza.",ez:"吃披萨我没问题。"},
{w:"that sucks",p:"/ðæt sʌks/",t:"phr.",z:"太糟了（口语）",e:"You have to work? That sucks.",ez:"你还得上班？太惨了。"},
{w:"hangry",p:"/ˈhæŋɡri/",t:"adj.",z:"饿到发脾气",e:"Sorry, I'm just hangry.",ez:"抱歉，我饿得发脾气了。"},
{w:"crash",p:"/kræʃ/",t:"v.",z:"（累到）倒头就睡；蹭住",e:"Can I crash here tonight?",ez:"我今晚能在这儿凑合一晚吗？"},
{w:"bail",p:"/beɪl/",t:"v.",z:"爽约，临时退出",e:"He bailed on us again.",ez:"他又放我们鸽子了。"},
{w:"crush",p:"/krʌʃ/",t:"n./v.",z:"暗恋对象",e:"I had a crush on her.",ez:"我曾经暗恋她。"},
{w:"awkward",p:"/ˈɔːkwərd/",t:"adj.",z:"尴尬的",e:"That was so awkward.",ez:"那场面太尴尬了。"},
{w:"sketchy",p:"/ˈsketʃi/",t:"adj.",z:"可疑的，不靠谱的",e:"That neighborhood is kinda sketchy.",ez:"那片儿有点乱。"},
{w:"legit",p:"/lɪˈdʒɪt/",t:"adj.",z:"真的，靠谱的",e:"Is this place legit?",ez:"这地方靠谱吗？"},
{w:"bucks",p:"/bʌks/",t:"n.",z:"美元（口语）",e:"It costs twenty bucks.",ez:"这要二十块。"},
/* --- 描述性格与人际 --- */
{w:"easygoing",p:"/ˌiːziˈɡoʊɪŋ/",t:"adj.",z:"随和的",e:"He's really easygoing.",ez:"他特别随和。"},
{w:"stubborn",p:"/ˈstʌbərn/",t:"adj.",z:"固执的",e:"Don't be so stubborn.",ez:"别这么固执。"},
{w:"thoughtful",p:"/ˈθɔːtfl/",t:"adj.",z:"体贴的；深思的",e:"That was very thoughtful of you.",ez:"你真贴心。"},
{w:"sensitive",p:"/ˈsensətɪv/",t:"adj.",z:"敏感的",e:"He's sensitive about his accent.",ez:"他对自己的口音很敏感。"},
{w:"outgoing",p:"/ˈaʊtɡoʊɪŋ/",t:"adj.",z:"外向的",e:"She's super outgoing.",ez:"她特别外向。"},
{w:"laid-back",p:"/leɪd bæk/",t:"adj.",z:"悠闲自在的",e:"He's really laid-back.",ez:"他特别随性。"},
{w:"picky",p:"/ˈpɪki/",t:"adj.",z:"挑剔的",e:"I'm picky about coffee.",ez:"我对咖啡很挑。"},
{w:"generous",p:"/ˈdʒenərəs/",t:"adj.",z:"慷慨的",e:"That's very generous of you.",ez:"您太慷慨了。"},
{w:"moody",p:"/ˈmuːdi/",t:"adj.",z:"喜怒无常的",e:"He's been moody all day.",ez:"他一整天都阴晴不定。"},
{w:"genuine",p:"/ˈdʒenjuɪn/",t:"adj.",z:"真诚的",e:"She seems genuine.",ez:"她看起来很真诚。"},
{w:"compromise",p:"/ˈkɑːmprəmaɪz/",t:"v./n.",z:"妥协",e:"We need to compromise.",ez:"我们需要各让一步。"},
{w:"apologize",p:"/əˈpɑːlədʒaɪz/",t:"v.",z:"道歉",e:"I apologize for the delay.",ez:"抱歉耽误了。"},
{w:"appreciate",p:"/əˈpriːʃieɪt/",t:"v.",z:"感激；欣赏",e:"I really appreciate it.",ez:"我真的很感激。"},
{w:"convince",p:"/kənˈvɪns/",t:"v.",z:"说服",e:"You convinced me.",ez:"你说服我了。"},
{w:"insist",p:"/ɪnˈsɪst/",t:"v.",z:"坚持",e:"He insisted on paying.",ez:"他坚持要付钱。"},
{w:"argue",p:"/ˈɑːrɡjuː/",t:"v.",z:"争论",e:"They argue all the time.",ez:"他们老是吵。"},
{w:"complain",p:"/kəmˈpleɪn/",t:"v.",z:"抱怨",e:"Stop complaining.",ez:"别抱怨了。"},
{w:"gossip",p:"/ˈɡɑːsɪp/",t:"n./v.",z:"八卦",e:"I don't like to gossip.",ez:"我不喜欢说八卦。"},
{w:"bond",p:"/bɑːnd/",t:"v./n.",z:"建立感情；纽带",e:"We bonded over music.",ez:"我们因为音乐熟了起来。"},
{w:"catch someone's eye",p:"/kætʃ ˈsʌmwʌnz aɪ/",t:"phr.",z:"吸引注意",e:"That poster caught my eye.",ez:"那张海报吸引了我的注意。"},
/* --- 工作 / 学业 --- */
{w:"apply for",p:"/əˈplaɪ fɔːr/",t:"phr.",z:"申请",e:"I applied for three jobs.",ez:"我申请了三份工作。"},
{w:"quit",p:"/kwɪt/",t:"v.",z:"辞职；戒掉",e:"I quit my job last month.",ez:"我上个月辞职了。"},
{w:"promote",p:"/prəˈmoʊt/",t:"v.",z:"升职；推广",e:"She got promoted.",ez:"她升职了。"},
{w:"feedback",p:"/ˈfiːdbæk/",t:"n.",z:"反馈意见",e:"Can I get some feedback?",ez:"能给点反馈吗？"},
{w:"brainstorm",p:"/ˈbreɪnstɔːrm/",t:"v./n.",z:"头脑风暴",e:"Let's brainstorm some ideas.",ez:"我们头脑风暴一下。"},
{w:"deadline driven",p:"/ˈdedlaɪn ˈdrɪvn/",t:"adj.",z:"受截止日期驱动的",e:"This job is deadline driven.",ez:"这工作全靠赶截止日期。"},
{w:"workload",p:"/ˈwɜːrkloʊd/",t:"n.",z:"工作量",e:"My workload is insane right now.",ez:"我现在工作量疯了。"},
{w:"multitask",p:"/ˌmʌltiˈtæsk/",t:"v.",z:"多任务处理",e:"I'm multitasking right now.",ez:"我现在在同时处理好几件事。"},
{w:"procrastinate",p:"/prəˈkræstɪneɪt/",t:"v.",z:"拖延",e:"Stop procrastinating.",ez:"别拖了。"},
{w:"cram",p:"/kræm/",t:"v.",z:"临时抱佛脚（cram for）",e:"I'm cramming for the exam.",ez:"我在临时抱佛脚备考。"},
{w:"pull an all-nighter",p:"/pʊl ən ɔːl ˈnaɪtər/",t:"phr.",z:"通宵",e:"I pulled an all-nighter.",ez:"我通宵了。"},
{w:"grade",p:"/ɡreɪd/",t:"n./v.",z:"分数；评分",e:"I got a good grade.",ez:"我得了高分。"},
{w:"assignment",p:"/əˈsaɪnmənt/",t:"n.",z:"作业，任务",e:"When is the assignment due?",ez:"作业什么时候交？"},
{w:"seminar",p:"/ˈsemɪnɑːr/",t:"n.",z:"研讨课",e:"I have a seminar at three.",ez:"我三点有研讨课。"},
{w:"syllabus",p:"/ˈsɪləbəs/",t:"n.",z:"课程大纲",e:"Check the syllabus.",ez:"看一下课程大纲。"},
{w:"scholarship",p:"/ˈskɑːlərʃɪp/",t:"n.",z:"奖学金",e:"I got a scholarship.",ez:"我拿到了奖学金。"},
{w:"major in",p:"/ˈmeɪdʒər ɪn/",t:"phr.",z:"主修",e:"I majored in economics.",ez:"我主修经济学。"},
{w:"internship",p:"/ˈɪntɜːrnʃɪp/",t:"n.",z:"实习",e:"I landed an internship.",ez:"我拿到了一份实习。"},
{w:"resume",p:"/ˈrezjumeɪ/",t:"n.",z:"简历",e:"Can you look over my resume?",ez:"能帮我看下简历吗？"},
{w:"interview",p:"/ˈɪntərvjuː/",t:"n./v.",z:"面试；采访",e:"How was the interview?",ez:"面试怎么样？"},
/* --- 科技与生活 --- */
{w:"dead battery",p:"/ded ˈbætəri/",t:"n.",z:"没电了",e:"My phone has a dead battery.",ez:"我手机没电了。"},
{w:"charger",p:"/ˈtʃɑːrdʒər/",t:"n.",z:"充电器",e:"Can I borrow your charger?",ez:"能借下充电器吗？"},
{w:"wifi",p:"/ˈwaɪfaɪ/",t:"n.",z:"无线网络",e:"What's the wifi password?",ez:"WiFi 密码是多少？"},
{w:"glitch",p:"/ɡlɪtʃ/",t:"n.",z:"小故障",e:"There's a glitch in the system.",ez:"系统有个小故障。"},
{w:"update",p:"/ˈʌpdeɪt/",t:"v./n.",z:"更新",e:"You should update the app.",ez:"你该更新一下应用。"},
{w:"download",p:"/ˈdaʊnloʊd/",t:"v./n.",z:"下载",e:"I downloaded a new app.",ez:"我下了个新应用。"},
{w:"password",p:"/ˈpæswɜːrd/",t:"n.",z:"密码",e:"I forgot my password.",ez:"我忘了密码。"},
{w:"scroll",p:"/skroʊl/",t:"v.",z:"滑动浏览",e:"I was just scrolling through my feed.",ez:"我刚在刷动态。"},
{w:"text me",p:"/tekst miː/",t:"phr.",z:"给我发短信",e:"Text me when you get home.",ez:"到家给我发消息。"},
{w:"ghosting",p:"/ˈɡoʊstɪŋ/",t:"n.",z:"突然失联不回消息",e:"He's totally ghosting me.",ez:"他完全不回我消息了。"},
{w:"spam",p:"/spæm/",t:"n.",z:"垃圾信息",e:"That went to my spam folder.",ez:"那进我垃圾箱了。"},
{w:"screenshot",p:"/ˈskriːnʃɑːt/",t:"n.",z:"截图",e:"Send me a screenshot.",ez:"发我个截图。"},
{w:"streaming",p:"/ˈstriːmɪŋ/",t:"n.",z:"流媒体",e:"I canceled my streaming service.",ez:"我把流媒体订阅取消了。"},
{w:"binge-watch",p:"/ˈbɪndʒ wɑːtʃ/",t:"v.",z:"刷剧",e:"I binge-watched the whole season.",ez:"我把整季刷完了。"},
{w:"subscription",p:"/səbˈskrɪpʃn/",t:"n.",z:"订阅",e:"I need to cancel a subscription.",ez:"我得取消个订阅。"},
/* --- 抽象与思维 --- */
{w:"attitude",p:"/ˈætɪtuːd/",t:"n.",z:"态度",e:"I don't like his attitude.",ez:"我不喜欢他的态度。"},
{w:"perspective",p:"/pərˈspektɪv/",t:"n.",z:"视角，看法",e:"Try to see it from my perspective.",ez:"试着从我的角度看。"},
{w:"priority",p:"/praɪˈɔːrəti/",t:"n.",z:"优先事项",e:"Family is my priority.",ez:"家庭是我的优先项。"},
{w:"opportunity",p:"/ˌɑːpərˈtuːnəti/",t:"n.",z:"机会",e:"That's a great opportunity.",ez:"这是个好机会。"},
{w:"challenge",p:"/ˈtʃælɪndʒ/",t:"n./v.",z:"挑战",e:"It's a real challenge.",ez:"这真是个挑战。"},
{w:"struggle",p:"/ˈstrʌɡl/",t:"v./n.",z:"挣扎，吃力",e:"I'm struggling with pronunciation.",ez:"我在发音上很吃力。"},
{w:"achievement",p:"/əˈtʃiːvmənt/",t:"n.",z:"成就",e:"That's a huge achievement.",ez:"那是巨大的成就。"},
{w:"motivation",p:"/ˌmoʊtɪˈveɪʃn/",t:"n.",z:"动力",e:"I lost my motivation.",ez:"我没动力了。"},
{w:"pressure",p:"/ˈpreʃər/",t:"n.",z:"压力",e:"He's under a lot of pressure.",ez:"他压力很大。"},
{w:"balance",p:"/ˈbæləns/",t:"n./v.",z:"平衡",e:"Work-life balance matters.",ez:"工作生活平衡很重要。"},
{w:"routine",p:"/ruːˈtiːn/",t:"n.",z:"日常惯例",e:"I have a morning routine.",ez:"我有晨间惯例。"},
{w:"habit",p:"/ˈhæbɪt/",t:"n.",z:"习惯",e:"I'm trying to build a habit.",ez:"我在试着养成习惯。"},
{w:"effort",p:"/ˈefərt/",t:"n.",z:"努力",e:"Thanks for the effort.",ez:"谢谢你的努力。"},
{w:"progress",p:"/ˈprɑːɡres/",t:"n./v.",z:"进步",e:"I'm making progress.",ez:"我在进步。"},
{w:"setback",p:"/ˈsetbæk/",t:"n.",z:"挫折",e:"It's just a small setback.",ez:"这只是个小挫折。"},
{w:"potential",p:"/pəˈtenʃl/",t:"n./adj.",z:"潜力；潜在的",e:"She has a lot of potential.",ez:"她很有潜力。"},
{w:"impact",p:"/ˈɪmpækt/",t:"n./v.",z:"影响",e:"It had a big impact on me.",ez:"这对我影响很大。"},
{w:"consequence",p:"/ˈkɑːnsəkwens/",t:"n.",z:"后果",e:"Think about the consequences.",ez:"想想后果。"},
{w:"benefit",p:"/ˈbenɪfɪt/",t:"n./v.",z:"好处；受益",e:"That's a big benefit.",ez:"那是个很大的好处。"},
{w:"drawback",p:"/ˈdrɔːbæk/",t:"n.",z:"缺点",e:"The only drawback is the price.",ez:"唯一的缺点是价格。"},
/* --- 更多高频实词 --- */
{w:"neighborhood",p:"/ˈneɪbərhʊd/",t:"n.",z:"街区，社区",e:"It's a quiet neighborhood.",ez:"这是个安静的社区。"},
{w:"landlord",p:"/ˈlændlɔːrd/",t:"n.",z:"房东",e:"I need to call my landlord.",ez:"我得给房东打电话。"},
{w:"utility",p:"/juːˈtɪləti/",t:"n.",z:"水电燃气等公用事业费",e:"Utilities are included.",ez:"水电费包含在内。"},
{w:"maintenance",p:"/ˈmeɪntənəns/",t:"n.",z:"维修，保养",e:"The AC needs maintenance.",ez:"空调需要维护。"},
{w:"lease",p:"/liːs/",t:"n./v.",z:"租约",e:"I signed a one-year lease.",ez:"我签了一年的租约。"},
{w:"furniture",p:"/ˈfɜːrnɪtʃər/",t:"n.",z:"家具",e:"The apartment comes furnished.",ez:"这公寓带家具。"},
{w:"gym",p:"/dʒɪm/",t:"n.",z:"健身房",e:"I hit the gym after work.",ez:"我下班后去健身房。"},
{w:"workout",p:"/ˈwɜːrkaʊt/",t:"n.",z:"锻炼",e:"I need a good workout.",ez:"我需要好好锻炼一下。"},
{w:"insurance premium",p:"/ɪnˈʃʊrəns ˈpriːmiəm/",t:"n.",z:"保险费",e:"The premium went up again.",ez:"保费又涨了。"},
{w:"customer service",p:"/ˈkʌstəmər ˈsɜːrvɪs/",t:"n.",z:"客服",e:"I called customer service.",ez:"我打给了客服。"},
{w:"on hold",p:"/ɑːn hoʊld/",t:"phr.",z:"（电话）等待中",e:"I've been on hold for ten minutes.",ez:"我已经等了十分钟了。"},
{w:"shipping",p:"/ˈʃɪpɪŋ/",t:"n.",z:"配送",e:"Shipping is free over $50.",ez:"满五十免运费。"},
{w:"in stock",p:"/ɪn stɑːk/",t:"phr.",z:"有货",e:"Is this in stock?",ez:"这个有货吗？"},
{w:"out of stock",p:"/aʊt əv stɑːk/",t:"phr.",z:"缺货",e:"Sorry, it's out of stock.",ez:"抱歉，缺货了。"},
{w:"sale rack",p:"/seɪl ræk/",t:"n.",z:"打折区货架",e:"Check the sale rack.",ez:"去打折区看看。"},
{w:"fitting room",p:"/ˈfɪtɪŋ ruːm/",t:"n.",z:"试衣间",e:"Where's the fitting room?",ez:"试衣间在哪？"},
{w:"run errands",p:"/rʌn ˈerəndz/",t:"phr.",z:"跑腿办事",e:"I've got errands to run.",ez:"我有一堆杂事要办。"},
{w:"grocery store",p:"/ˈɡroʊsəri stɔːr/",t:"n.",z:"杂货店，超市",e:"I'm going to the grocery store.",ez:"我要去趟超市。"},
{w:"hardware store",p:"/ˈhɑːrdwer stɔːr/",t:"n.",z:"五金店",e:"Pick it up at the hardware store.",ez:"去五金店买。"},
{w:"dry cleaner",p:"/draɪ ˈkliːnər/",t:"n.",z:"干洗店",e:"I dropped it off at the dry cleaner.",ez:"我把它送干洗店了。"},
{w:"salad bar",p:"/ˈsæləd bɑːr/",t:"n.",z:"沙拉吧",e:"I just got the salad bar.",ez:"我只拿了沙拉。"},
{w:"drive-thru",p:"/draɪv θruː/",t:"n.",z:"免下车通道",e:"Let's just hit the drive-thru.",ez:"咱们走免下车通道吧。"},
{w:"brunch",p:"/brʌntʃ/",t:"n.",z:"早午餐",e:"Brunch on Sunday?",ez:"周日吃早午餐？"},
{w:"potluck",p:"/ˈpɑːtlʌk/",t:"n.",z:"百味餐（各带一道菜）",e:"It's a potluck, so bring something.",ez:"是百味餐，带点东西来。"},
{w:"left a message",p:"/left ə ˈmesɪdʒ/",t:"phr.",z:"留了言",e:"I left a message on his voicemail.",ez:"我在他语音信箱留了言。"},
{w:"voicemail",p:"/ˈvɔɪsmeɪl/",t:"n.",z:"语音信箱",e:"It went straight to voicemail.",ez:"直接转语音信箱了。"},
{w:"area code",p:"/ˈeriə koʊd/",t:"n.",z:"区号",e:"What's your area code?",ez:"你区号是多少？"},
{w:"zip code",p:"/zɪp koʊd/",t:"n.",z:"邮编",e:"Can I get your zip code?",ez:"能给下邮编吗？"},
{w:"social security",p:"/ˈsoʊʃl sɪˈkjʊrəti/",t:"n.",z:"社会保障（号）",e:"Do you have a social security number?",ez:"你有社安号吗？"},
{w:"small talk",p:"/smɔːl tɔːk/",t:"n.",z:"闲聊",e:"I'm terrible at small talk.",ez:"我特别不会闲聊。"},
{w:"body language",p:"/ˈbɑːdi ˈlæŋɡwɪdʒ/",t:"n.",z:"肢体语言",e:"Watch their body language.",ez:"注意他们的肢体语言。"},
{w:"sarcasm",p:"/ˈsɑːrkæzəm/",t:"n.",z:"讽刺，反话",e:"Was that sarcasm?",ez:"那是反话吧？"},
{w:"personal space",p:"/ˈpɜːrsənl speɪs/",t:"n.",z:"个人空间",e:"Americans value personal space.",ez:"美国人很看重个人空间。"},
{w:"tipping culture",p:"/ˈtɪpɪŋ ˈkʌltʃər/",t:"n.",z:"小费文化",e:"Tipping culture here is intense.",ez:"这里的小费文化很重。"},
{w:"rush hour",p:"/rʌʃ ˈaʊər/",t:"n.",z:"高峰期",e:"Avoid rush hour if you can.",ez:"尽量避开高峰期。"},
{w:"remote work",p:"/rɪˈmoʊt wɜːrk/",t:"n.",z:"远程办公",e:"I do remote work now.",ez:"我现在远程办公。"},
{w:"burnout",p:"/ˈbɜːrnaʊt/",t:"n.",z:"职业倦怠",e:"I'm close to burnout.",ez:"我快倦怠了。"},
{w:"networking",p:"/ˈnetwɜːrkɪŋ/",t:"n.",z:"人脉拓展",e:"It's a networking event.",ez:"这是场社交活动。"},
{w:"follow up",p:"/ˈfɑːloʊ ʌp/",t:"phr.",z:"跟进",e:"I'll follow up with an email.",ez:"我会发邮件跟进。"},
{w:"touch base",p:"/tʌtʃ beɪs/",t:"phr.",z:"碰一下，沟通进展",e:"Let's touch base next week.",ez:"下周我们碰一下。"},
{w:"on the same page",p:"/ɑːn ðə seɪm peɪdʒ/",t:"phr.",z:"意见一致",e:"Are we on the same page?",ez:"我们意见一致吗？"},
{w:"ballpark figure",p:"/ˈbɔːlpɑːrk ˈfɪɡjər/",t:"n.",z:"大致数字",e:"Just give me a ballpark figure.",ez:"给我个大概数字就行。"},
{w:"bottom line",p:"/ˈbɑːtəm laɪn/",t:"n.",z:"底线；核心结论",e:"The bottom line is we're over budget.",ez:"核心是我们超预算了。"},
{w:"learn the ropes",p:"/lɜːrn ðə roʊps/",t:"phr.",z:"熟悉门道",e:"I'm still learning the ropes.",ez:"我还在摸门道。"},
{w:"get the hang of",p:"/ɡet ðə hæŋ əv/",t:"phr.",z:"掌握窍门",e:"I'm getting the hang of it.",ez:"我慢慢上手了。"},
{w:"in the long run",p:"/ɪn ðə lɔːŋ rʌn/",t:"phr.",z:"从长远看",e:"It pays off in the long run.",ez:"长远来看是值得的。"},
{w:"take it easy",p:"/teɪk ɪt ˈiːzi/",t:"phr.",z:"放松点；慢走",e:"Take it easy, alright?",ez:"放松点，好吗？"},
{w:"what's up",p:"/wʌts ʌp/",t:"phr.",z:"最近咋样（打招呼）",e:"Hey! What's up?",ez:"嘿！最近怎么样？"},
{w:"how's it going",p:"/haʊz ɪt ˈɡoʊɪŋ/",t:"phr.",z:"最近好吗",e:"How's it going, man?",ez:"最近好吗，兄弟？"},
{w:"long time no see",p:"/lɔːŋ taɪm noʊ siː/",t:"phr.",z:"好久不见",e:"Long time no see!",ez:"好久不见！"},
{w:"help yourself",p:"/help jɔːrˈself/",t:"phr.",z:"随便吃/自便",e:"Help yourself to some snacks.",ez:"零食随便吃。"},
{w:"make yourself at home",p:"/meɪk jɔːrˈself ət hoʊm/",t:"phr.",z:"别客气，当自己家",e:"Make yourself at home.",ez:"别客气，当自己家。"}
];
