/* 词库 ④：托福（TOEFL）学术核心词 —— 覆盖真题讲座高频学科词（生物/地质/天文/历史/心理/艺术） */
window.VOCAB_TOEFL = [
/* --- 生物学 --- */
{w:"adaptation",p:"/ˌædæpˈteɪʃn/",t:"n.",z:"适应；适应性特征",e:"This is an adaptation to cold climates.",ez:"这是对寒冷气候的一种适应。"},
{w:"habitat",p:"/ˈhæbɪtæt/",t:"n.",z:"栖息地",e:"The habitat is being destroyed.",ez:"栖息地正被破坏。"},
{w:"species",p:"/ˈspiːʃiːz/",t:"n.",z:"物种",e:"Many species are endangered.",ez:"许多物种濒临灭绝。"},
{w:"predator",p:"/ˈpredətər/",t:"n.",z:"捕食者",e:"Predators control the population.",ez:"捕食者控制着种群数量。"},
{w:"prey",p:"/preɪ/",t:"n./v.",z:"猎物",e:"The hawk spotted its prey.",ez:"鹰发现了猎物。"},
{w:"mammal",p:"/ˈmæml/",t:"n.",z:"哺乳动物",e:"Whales are marine mammals.",ez:"鲸是海洋哺乳动物。"},
{w:"metabolism",p:"/məˈtæbəlɪzəm/",t:"n.",z:"新陈代谢",e:"Hibernation slows the metabolism.",ez:"冬眠会减缓新陈代谢。"},
{w:"hibernation",p:"/ˌhaɪbərˈneɪʃn/",t:"n.",z:"冬眠",e:"Bears enter hibernation in winter.",ez:"熊在冬天进入冬眠。"},
{w:"migration",p:"/maɪˈɡreɪʃn/",t:"n.",z:"迁徙",e:"Bird migration begins in autumn.",ez:"鸟类迁徙在秋季开始。"},
{w:"reproduce",p:"/ˌriːprəˈduːs/",t:"v.",z:"繁殖",e:"They reproduce once a year.",ez:"它们每年繁殖一次。"},
{w:"offspring",p:"/ˈɔːfsprɪŋ/",t:"n.",z:"后代",e:"Parents protect their offspring.",ez:"亲代保护它们的后代。"},
{w:"evolution",p:"/ˌevəˈluːʃn/",t:"n.",z:"进化",e:"Evolution explains this diversity.",ez:"进化解释了这种多样性。"},
{w:"genetic",p:"/dʒəˈnetɪk/",t:"adj.",z:"基因的",e:"It's a genetic trait.",ez:"这是一种遗传特征。"},
{w:"mutation",p:"/mjuːˈteɪʃn/",t:"n.",z:"突变",e:"A mutation caused the change.",ez:"一次突变导致了这一变化。"},
{w:"organism",p:"/ˈɔːrɡənɪzəm/",t:"n.",z:"生物体",e:"Every organism needs energy.",ez:"每个生物体都需要能量。"},
{w:"cell",p:"/sel/",t:"n.",z:"细胞",e:"Cells divide rapidly.",ez:"细胞快速分裂。"},
{w:"enzyme",p:"/ˈenzaɪm/",t:"n.",z:"酶",e:"Enzymes speed up reactions.",ez:"酶加速反应。"},
{w:"bacteria",p:"/bækˈtɪriə/",t:"n.",z:"细菌",e:"Some bacteria are beneficial.",ez:"有些细菌是有益的。"},
{w:"symbiosis",p:"/ˌsɪmbaɪˈoʊsɪs/",t:"n.",z:"共生",e:"It's a case of symbiosis.",ez:"这是一个共生的例子。"},
{w:"photosynthesis",p:"/ˌfoʊtoʊˈsɪnθəsɪs/",t:"n.",z:"光合作用",e:"Photosynthesis produces oxygen.",ez:"光合作用产生氧气。"},
{w:"ecosystem",p:"/ˈiːkoʊsɪstəm/",t:"n.",z:"生态系统",e:"The whole ecosystem collapsed.",ez:"整个生态系统崩溃了。"},
{w:"extinction",p:"/ɪkˈstɪŋkʃn/",t:"n.",z:"灭绝",e:"Mass extinction occurred then.",ez:"那时发生了大灭绝。"},
{w:"fossil",p:"/ˈfɑːsl/",t:"n.",z:"化石",e:"The fossil dates back 100 million years.",ez:"这块化石可追溯到一亿年前。"},
{w:"camouflage",p:"/ˈkæməflɑːʒ/",t:"n./v.",z:"伪装",e:"Its colour acts as camouflage.",ez:"它的颜色起到伪装作用。"},
{w:"nutrient",p:"/ˈnuːtriənt/",t:"n.",z:"营养物",e:"The soil lacks nutrients.",ez:"土壤缺乏养分。"},
/* --- 地质 / 地球科学 --- */
{w:"sediment",p:"/ˈsedɪmənt/",t:"n.",z:"沉积物",e:"Layers of sediment built up.",ez:"沉积层逐渐堆积。"},
{w:"erosion",p:"/ɪˈroʊʒn/",t:"n.",z:"侵蚀",e:"Erosion shaped the valley.",ez:"侵蚀塑造了这条峡谷。"},
{w:"glacier",p:"/ˈɡleɪʃər/",t:"n.",z:"冰川",e:"The glacier is retreating.",ez:"冰川正在退缩。"},
{w:"volcano",p:"/vɑːlˈkeɪnoʊ/",t:"n.",z:"火山",e:"The volcano erupted last year.",ez:"这座火山去年喷发了。"},
{w:"magma",p:"/ˈmæɡmə/",t:"n.",z:"岩浆",e:"Magma rose to the surface.",ez:"岩浆上升到地表。"},
{w:"crust",p:"/krʌst/",t:"n.",z:"地壳",e:"The earth's crust is thin here.",ez:"这里地壳很薄。"},
{w:"tectonic plate",p:"/tekˈtɑːnɪk pleɪt/",t:"n.",z:"构造板块",e:"Tectonic plates move slowly.",ez:"构造板块缓慢移动。"},
{w:"earthquake",p:"/ˈɜːrθkweɪk/",t:"n.",z:"地震",e:"The earthquake measured 7.0.",ez:"这次地震为7.0级。"},
{w:"mineral",p:"/ˈmɪnrəl/",t:"n.",z:"矿物",e:"The rock contains rare minerals.",ez:"这种岩石含有稀有矿物。"},
{w:"fossil fuel",p:"/ˈfɑːsl fjuːəl/",t:"n.",z:"化石燃料",e:"Fossil fuels cause emissions.",ez:"化石燃料造成排放。"},
{w:"atmosphere",p:"/ˈætməsfɪr/",t:"n.",z:"大气层",e:"The atmosphere traps heat.",ez:"大气层锁住了热量。"},
{w:"climate",p:"/ˈklaɪmət/",t:"n.",z:"气候",e:"The climate changed dramatically.",ez:"气候发生了剧烈变化。"},
{w:"precipitation",p:"/prɪˌsɪpɪˈteɪʃn/",t:"n.",z:"降水",e:"Annual precipitation is low.",ez:"年降水量很低。"},
{w:"humidity",p:"/hjuːˈmɪdəti/",t:"n.",z:"湿度",e:"High humidity makes it worse.",ez:"高湿度让情况更糟。"},
{w:"continental drift",p:"/ˌkɑːntɪˈnentl drɪft/",t:"n.",z:"大陆漂移",e:"Continental drift explains this.",ez:"大陆漂移解释了这一点。"},
{w:"core sample",p:"/kɔːr ˈsæmpl/",t:"n.",z:"岩芯样本",e:"They analysed a core sample.",ez:"他们分析了一份岩芯样本。"},
{w:"radiocarbon dating",p:"/ˌreɪdioʊˈkɑːrbən ˈdeɪtɪŋ/",t:"n.",z:"放射性碳定年",e:"Radiocarbon dating gives the age.",ez:"碳定年给出了年代。"},
/* --- 天文学 --- */
{w:"galaxy",p:"/ˈɡæləksi/",t:"n.",z:"星系",e:"Our galaxy has billions of stars.",ez:"我们的星系有数十亿颗恒星。"},
{w:"orbit",p:"/ˈɔːrbɪt/",t:"n./v.",z:"轨道；绕轨运行",e:"The moon orbits the earth.",ez:"月球绕地球运行。"},
{w:"telescope",p:"/ˈtelɪskoʊp/",t:"n.",z:"望远镜",e:"The telescope revealed new data.",ez:"望远镜揭示了新数据。"},
{w:"asteroid",p:"/ˈæstərɔɪd/",t:"n.",z:"小行星",e:"An asteroid hit the earth.",ez:"一颗小行星撞击了地球。"},
{w:"comet",p:"/ˈkɑːmɪt/",t:"n.",z:"彗星",e:"The comet appears every 76 years.",ez:"这颗彗星每76年出现一次。"},
{w:"gravity",p:"/ˈɡrævəti/",t:"n.",z:"重力",e:"Gravity keeps us grounded.",ez:"重力使我们留在地面上。"},
{w:"radiation",p:"/ˌreɪdiˈeɪʃn/",t:"n.",z:"辐射",e:"The sun emits radiation.",ez:"太阳发出辐射。"},
{w:"satellite",p:"/ˈsætəlaɪt/",t:"n.",z:"卫星",e:"The satellite sends images.",ez:"卫星传回图像。"},
{w:"solar system",p:"/ˈsoʊlər ˈsɪstəm/",t:"n.",z:"太阳系",e:"Eight planets in the solar system.",ez:"太阳系有八颗行星。"},
{w:"supernova",p:"/ˌsuːpərˈnoʊvə/",t:"n.",z:"超新星",e:"A supernova exploded nearby.",ez:"附近爆发了一颗超新星。"},
/* --- 历史 / 考古 / 人类学 --- */
{w:"civilization",p:"/ˌsɪvələˈzeɪʃn/",t:"n.",z:"文明",e:"A ancient civilization flourished here.",ez:"一个古老文明曾在此繁荣。"},
{w:"artifact",p:"/ˈɑːrtɪfækt/",t:"n.",z:"人工制品，文物",e:"They uncovered stone artifacts.",ez:"他们发现了石器文物。"},
{w:"excavation",p:"/ˌekskəˈveɪʃn/",t:"n.",z:"发掘",e:"The excavation took three years.",ez:"发掘工作历时三年。"},
{w:"ancestor",p:"/ˈænsestər/",t:"n.",z:"祖先",e:"Our ancestors farmed this land.",ez:"我们的祖先耕种这片土地。"},
{w:"settlement",p:"/ˈsetlmənt/",t:"n.",z:"定居点",e:"The settlement dates to 2000 BC.",ez:"该定居点可追溯到公元前2000年。"},
{w:"dynasty",p:"/ˈdaɪnəsti/",t:"n.",z:"朝代",e:"The dynasty lasted 300 years.",ez:"这个王朝延续了三百年。"},
{w:"empire",p:"/ˈempaɪər/",t:"n.",z:"帝国",e:"The empire collapsed suddenly.",ez:"帝国突然瓦解。"},
{w:"trade route",p:"/treɪd ruːt/",t:"n.",z:"贸易路线",e:"Control the trade route.",ez:"控制贸易路线。"},
{w:"medieval",p:"/ˌmiːdˈiːvl/",t:"adj.",z:"中世纪的",e:"Medieval towns were crowded.",ez:"中世纪的城镇很拥挤。"},
{w:"revolution",p:"/ˌrevəˈluːʃn/",t:"n.",z:"革命；巨变",e:"The Industrial Revolution.",ez:"工业革命。"},
{w:"colonize",p:"/ˈkɑːlənaɪz/",t:"v.",z:"殖民",e:"They colonized the region.",ez:"他们殖民了该地区。"},
{w:"archaeology",p:"/ˌɑːrkiˈɑːlədʒi/",t:"n.",z:"考古学",e:"She studies archaeology.",ez:"她研究考古学。"},
{w:"ritual",p:"/ˈrɪtʃuəl/",t:"n./adj.",z:"仪式",e:"It was used in religious rituals.",ez:"它被用于宗教仪式。"},
{w:"nomadic",p:"/noʊˈmædɪk/",t:"adj.",z:"游牧的",e:"Nomadic tribes moved seasonally.",ez:"游牧部落季节性迁徙。"},
{w:"agriculture",p:"/ˈæɡrɪkʌltʃər/",t:"n.",z:"农业",e:"Agriculture began 10,000 years ago.",ez:"农业始于一万年前。"},
/* --- 心理学 / 社会科学 --- */
{w:"cognition",p:"/kɑːɡˈnɪʃn/",t:"n.",z:"认知",e:"Cognition develops with age.",ez:"认知随年龄发展。"},
{w:"behavior",p:"/bɪˈheɪvjər/",t:"n.",z:"行为",e:"The behavior was observed.",ez:"该行为被观察到了。"},
{w:"stimulus",p:"/ˈstɪmjələs/",t:"n.",z:"刺激",e:"The response to a stimulus.",ez:"对刺激的反应。"},
{w:"perception",p:"/pərˈsepʃn/",t:"n.",z:"感知，认知",e:"Perception varies between people.",ez:"人与人之间感知不同。"},
{w:"memory",p:"/ˈmeməri/",t:"n.",z:"记忆",e:"Short-term memory is limited.",ez:"短期记忆是有限的。"},
{w:"hypothesis",p:"/haɪˈpɑːθəsɪs/",t:"n.",z:"假设",e:"The hypothesis was tested.",ez:"假设得到了检验。"},
{w:"experiment",p:"/ɪkˈsperɪmənt/",t:"n./v.",z:"实验",e:"The experiment proved the point.",ez:"实验证明了这一点。"},
{w:"observation",p:"/ˌɑːbzərˈveɪʃn/",t:"n.",z:"观察",e:"Careful observation is key.",ez:"仔细的观察是关键。"},
{w:"variable",p:"/ˈveriəbl/",t:"n./adj.",z:"变量；可变的",e:"We controlled every variable.",ez:"我们控制了每个变量。"},
{w:"correlation",p:"/ˌkɔːrəˈleɪʃn/",t:"n.",z:"相关性",e:"There's a strong correlation.",ez:"有很强的相关性。"},
{w:"causality",p:"/kɔːˈzæləti/",t:"n.",z:"因果关系",e:"Correlation isn't causality.",ez:"相关性不等于因果。"},
{w:"motivation",p:"/ˌmoʊtɪˈveɪʃn/",t:"n.",z:"动机",e:"Intrinsic motivation matters.",ez:"内在动机很重要。"},
{w:"conditioning",p:"/kənˈdɪʃənɪŋ/",t:"n.",z:"条件反射",e:"Classical conditioning was demonstrated.",ez:"经典条件反射得到了证明。"},
{w:"socialization",p:"/ˌsoʊʃələˈzeɪʃn/",t:"n.",z:"社会化",e:"Socialization begins in childhood.",ez:"社会化始于童年。"},
{w:"conformity",p:"/kənˈfɔːrməti/",t:"n.",z:"从众",e:"The study showed conformity.",ez:"该研究显示了从众行为。"},
{w:"cognitive dissonance",p:"/ˈkɑːɡnətɪv ˈdɪsənəns/",t:"n.",z:"认知失调",e:"It causes cognitive dissonance.",ez:"这导致了认知失调。"},
/* --- 艺术 / 文学 / 建筑 --- */
{w:"renaissance",p:"/ˈrenəsɑːns/",t:"n.",z:"文艺复兴",e:"The Renaissance changed art.",ez:"文艺复兴改变了艺术。"},
{w:"sculpture",p:"/ˈskʌlptʃər/",t:"n.",z:"雕塑",e:"The sculpture is marble.",ez:"这座雕塑是大理石的。"},
{w:"mural",p:"/ˈmjʊrəl/",t:"n.",z:"壁画",e:"The mural covers three walls.",ez:"壁画覆盖了三面墙。"},
{w:"aesthetic",p:"/esˈθetɪk/",t:"adj.",z:"审美的",e:"It has great aesthetic value.",ez:"它有很高的美学价值。"},
{w:"composition",p:"/ˌkɑːmpəˈzɪʃn/",t:"n.",z:"构图；作品",e:"The composition is balanced.",ez:"构图很均衡。"},
{w:"Genre",p:"/ˈʒɑːnrə/",t:"n.",z:"体裁，类型",e:"It's a new genre of writing.",ez:"这是一种新的写作体裁。"},
{w:"metaphor",p:"/ˈmetəfɔːr/",t:"n.",z:"隐喻",e:"The poem uses a metaphor.",ez:"这首诗使用了隐喻。"},
{w:"narrative",p:"/ˈnærətɪv/",t:"n.",z:"叙事",e:"The narrative shifts in chapter two.",ez:"叙事在第二章发生转变。"},
{w:"criticism",p:"/ˈkrɪtɪsɪzəm/",t:"n.",z:"批评；评论",e:"The play drew harsh criticism.",ez:"该剧招致严厉批评。"},
{w:"exhibition",p:"/ˌeksɪˈbɪʃn/",t:"n.",z:"展览",e:"The exhibition runs till May.",ez:"展览持续到五月。"},
{w:"architecture",p:"/ˈɑːrkɪtektʃər/",t:"n.",z:"建筑",e:"Modern architecture values function.",ez:"现代建筑重视功能。"},
{w:"arch",p:"/ɑːrtʃ/",t:"n.",z:"拱",e:"The arch supports the roof.",ez:"拱支撑着屋顶。"},
{w:"facade",p:"/fəˈsɑːd/",t:"n.",z:"（建筑）立面",e:"The facade was restored.",ez:"立面得到了修复。"},
{w:"symphony",p:"/ˈsɪmfəni/",t:"n.",z:"交响乐",e:"His fifth symphony.",ez:"他的第五交响曲。"},
{w:"improvisation",p:"/ɪmˌprɑːvəˈzeɪʃn/",t:"n.",z:"即兴创作",e:"Jazz relies on improvisation.",ez:"爵士乐依赖即兴创作。"},
/* --- 经济 / 商业 --- */
{w:"supply and demand",p:"/səˈplaɪ ənd dɪˈmænd/",t:"n.",z:"供需",e:"Supply and demand set the price.",ez:"供需决定价格。"},
{w:"inflation",p:"/ɪnˈfleɪʃn/",t:"n.",z:"通货膨胀",e:"Inflation rose to five percent.",ez:"通胀升至5%。"},
{w:"revenue",p:"/ˈrevənuː/",t:"n.",z:"收入，营收",e:"Revenue increased by 20%.",ez:"营收增长了20%。"},
{w:"profit margin",p:"/ˈprɑːfɪt ˈmɑːrdʒɪn/",t:"n.",z:"利润率",e:"The profit margin is thin.",ez:"利润率很薄。"},
{w:"monopoly",p:"/məˈnɑːpəli/",t:"n.",z:"垄断",e:"The company has a monopoly.",ez:"这家公司处于垄断地位。"},
{w:"entrepreneur",p:"/ˌɑːntrəprəˈnɜːr/",t:"n.",z:"创业者",e:"She's a successful entrepreneur.",ez:"她是位成功的创业者。"},
{w:"investment",p:"/ɪnˈvestmənt/",t:"n.",z:"投资",e:"It requires huge investment.",ez:"这需要巨额投资。"},
{w:"tariff",p:"/ˈtærɪf/",t:"n.",z:"关税",e:"Tariffs raise prices.",ez:"关税推高了价格。"},
{w:"subsidy",p:"/ˈsʌbsədi/",t:"n.",z:"补贴",e:"The subsidy was cut.",ez:"补贴被削减了。"},
{w:"efficiency",p:"/ɪˈfɪʃnsi/",t:"n.",z:"效率",e:"It improves efficiency.",ez:"它提高了效率。"},
{w:"productivity",p:"/ˌproʊdʌkˈtɪvəti/",t:"n.",z:"生产率",e:"Productivity doubled.",ez:"生产率翻了一倍。"},
{w:"market share",p:"/ˈmɑːrkɪt ʃer/",t:"n.",z:"市场份额",e:"They lost market share.",ez:"他们失去了市场份额。"},
/* --- 学术语篇与校园场景 --- */
{w:"hypothesize",p:"/haɪˈpɑːθəsaɪz/",t:"v.",z:"假设，推测",e:"Scientists hypothesize that…",ez:"科学家推测……"},
{w:"empirical",p:"/ɪmˈpɪrɪkl/",t:"adj.",z:"实证的",e:"There's empirical evidence.",ez:"有实证依据。"},
{w:"validity",p:"/vəˈlɪdəti/",t:"n.",z:"有效性",e:"The validity is questionable.",ez:"有效性存疑。"},
{w:"controversy",p:"/ˈkɑːntrəvɜːrsi/",t:"n.",z:"争议",e:"The theory caused controversy.",ez:"该理论引发争议。"},
{w:"consensus",p:"/kənˈsensəs/",t:"n.",z:"共识",e:"There's no consensus yet.",ez:"目前尚无共识。"},
{w:"cite",p:"/saɪt/",t:"v.",z:"引用",e:"You must cite your sources.",ez:"你必须注明来源。"},
{w:"abstract",p:"/ˈæbstrækt/",t:"n./adj.",z:"摘要；抽象的",e:"Read the abstract first.",ez:"先读摘要。"},
{w:"dissertation",p:"/ˌdɪsərˈteɪʃn/",t:"n.",z:"学位论文",e:"I'm writing my dissertation.",ez:"我在写学位论文。"},
{w:"undergraduate",p:"/ˌʌndərˈɡrædʒuət/",t:"n.",z:"本科生",e:"It's for undergraduates only.",ez:"只面向本科生。"},
{w:"prerequisite",p:"/ˌpriːˈrekwəzɪt/",t:"n.",z:"先修课程",e:"It's a prerequisite for this class.",ez:"这是这门课的先修要求。"},
{w:"syllabus",p:"/ˈsɪləbəs/",t:"n.",z:"教学大纲",e:"It's on the syllabus.",ez:"这在大纲里。"},
{w:"office hours",p:"/ˈɔːfɪs ˈaʊərz/",t:"n.",z:"答疑时间",e:"Come to my office hours.",ez:"来我的答疑时间。"},
{w:"registration",p:"/ˌredʒɪˈstreɪʃn/",t:"n.",z:"注册，选课",e:"Registration opens Monday.",ez:"周一开始注册。"},
{w:"transcript",p:"/ˈtrænskrɪpt/",t:"n.",z:"成绩单",e:"Request an official transcript.",ez:"申请一份官方成绩单。"},
{w:"dormitory",p:"/ˈdɔːrmətɔːri/",t:"n.",z:"宿舍",e:"I live in a dormitory.",ez:"我住在宿舍。"},
{w:"cafeteria",p:"/ˌkæfəˈtɪriə/",t:"n.",z:"食堂",e:"Meet me at the cafeteria.",ez:"食堂见。"},
{w:"extension",p:"/ɪkˈstenʃn/",t:"n.",z:"延期",e:"Can I get an extension?",ez:"我能延期吗？"},
{w:"plagiarism",p:"/ˈpleɪdʒərɪzəm/",t:"n.",z:"剽窃",e:"Plagiarism is a serious offense.",ez:"剽窃是严重违规。"},
{w:"deadline",p:"/ˈdedlaɪn/",t:"n.",z:"截止日期",e:"I need an extension on the deadline.",ez:"我需要延长截止日期。"},
{w:"peer review",p:"/pɪr rɪˈvjuː/",t:"n.",z:"同行评审",e:"It passed peer review.",ez:"它通过了同行评审。"},
{w:"fieldwork",p:"/ˈfiːldwɜːrk/",t:"n.",z:"田野调查",e:"She did fieldwork in Kenya.",ez:"她在肯尼亚做了田野调查。"},
{w:"quantitative",p:"/ˈkwɑːntəteɪtɪv/",t:"adj.",z:"定量的",e:"We used quantitative methods.",ez:"我们使用了定量方法。"},
{w:"qualitative",p:"/ˈkwɑːləteɪtɪv/",t:"adj.",z:"定性的",e:"Qualitative data adds depth.",ez:"定性数据增加了深度。"},
{w:"longitudinal",p:"/ˌlɑːndʒəˈtuːdnl/",t:"adj.",z:"纵向的（长期追踪）",e:"A longitudinal study over ten years.",ez:"一项历时十年的纵向研究。"},
{w:"sample size",p:"/ˈsæmpl saɪz/",t:"n.",z:"样本量",e:"The sample size was too small.",ez:"样本量太小了。"},
{w:"bias",p:"/ˈbaɪəs/",t:"n.",z:"偏差，偏见",e:"The results may contain bias.",ez:"结果可能存在偏差。"},
{w:"anomaly",p:"/əˈnɑːməli/",t:"n.",z:"异常现象",e:"That's an anomaly in the data.",ez:"那是数据中的一个异常值。"},
{w:"preliminary",p:"/prɪˈlɪmɪneri/",t:"adj.",z:"初步的",e:"These are preliminary results.",ez:"这些是初步结果。"},
{w:"subsequent",p:"/ˈsʌbsɪkwənt/",t:"adj.",z:"随后的",e:"Subsequent studies confirmed it.",ez:"后续研究证实了这一点。"},
{w:"furthermore",p:"/ˌfɜːrðərˈmɔːr/",t:"adv.",z:"此外",e:"Furthermore, it saves money.",ez:"此外，它还省钱。"},
{w:"nevertheless",p:"/ˌnevərðəˈles/",t:"adv.",z:"然而，尽管如此",e:"Nevertheless, problems remain.",ez:"尽管如此，问题依然存在。"},
{w:"consequently",p:"/ˈkɑːnsəkwentli/",t:"adv.",z:"因此",e:"Consequently, prices rose.",ez:"因此，价格上涨了。"},
{w:"in terms of",p:"/ɪn tɜːrmz əv/",t:"phr.",z:"就…而言",e:"In terms of cost, it's better.",ez:"就成本而言，它更好。"},
{w:"with respect to",p:"/wɪð rɪˈspekt tuː/",t:"phr.",z:"关于，就…来说",e:"With respect to your question…",ez:"关于您的问题……"},
{w:"take into account",p:"/teɪk ˈɪntuː əˈkaʊnt/",t:"phr.",z:"考虑到",e:"Take all factors into account.",ez:"把所有因素都考虑进去。"}
];
