/* 词库 ①：美国日常核心 —— 最高频功能词/态度词/基础动词
   w=单词 p=音标 t=词性 z=中文 e=例句 ez=例句翻译 */
window.VOCAB_CORE = [
/* --- 态度与语气（听力里出现频率极高） --- */
{w:"actually",p:"/ˈæktʃuəli/",t:"adv.",z:"实际上；其实（口语高频语气词）",e:"Actually, I was gonna call you tonight.",ez:"其实我今晚正准备给你打电话。"},
{w:"basically",p:"/ˈbeɪsɪkli/",t:"adv.",z:"基本上；说白了",e:"It's basically the same thing.",ez:"说白了就是同一回事。"},
{w:"literally",p:"/ˈlɪtərəli/",t:"adv.",z:"字面上；真的（口语夸张强调）",e:"I literally have no idea what he said.",ez:"我真的一点没听懂他说啥。"},
{w:"obviously",p:"/ˈɑːbviəsli/",t:"adv.",z:"显然",e:"He's obviously not coming.",ez:"他显然不会来了。"},
{w:"honestly",p:"/ˈɑːnɪstli/",t:"adv.",z:"说实话",e:"Honestly, I'd rather stay home.",ez:"说实话我宁愿待在家。"},
{w:"anyway",p:"/ˈeniweɪ/",t:"adv.",z:"不管怎样；话说回来",e:"Anyway, let's get back to work.",ez:"不管怎样，我们回到正事吧。"},
{w:"though",p:"/ðoʊ/",t:"adv.",z:"不过（句末表转折，超高频）",e:"It was fun though.",ez:"不过还挺好玩的。"},
{w:"whatever",p:"/wətˈevər/",t:"adv./pron.",z:"随便；无所谓",e:"Do whatever you want.",ez:"你想干嘛就干嘛。"},
{w:"maybe",p:"/ˈmeɪbi/",t:"adv.",z:"也许",e:"Maybe we should leave early.",ez:"也许我们该早点走。"},
{w:"probably",p:"/ˈprɑːbəbli/",t:"adv.",z:"大概，很可能",e:"It'll probably rain later.",ez:"待会儿很可能会下雨。"},
{w:"definitely",p:"/ˈdefɪnətli/",t:"adv.",z:"肯定，一定",e:"I'll definitely be there.",ez:"我一定到。"},
{w:"exactly",p:"/ɪɡˈzæktli/",t:"adv.",z:"正是；完全正确",e:"Exactly what I was thinking.",ez:"正是我在想的事。"},
{w:"apparently",p:"/əˈpærəntli/",t:"adv.",z:"据说；显然",e:"Apparently they broke up.",ez:"据说他们分手了。"},
{w:"seriously",p:"/ˈsɪriəsli/",t:"adv.",z:"认真地；不会吧",e:"Are you serious? — Yes, seriously.",ez:"你认真的？——是的，认真的。"},
{w:"hopefully",p:"/ˈhoʊpfəli/",t:"adv.",z:"希望如此（美语极常用）",e:"Hopefully it won't take long.",ez:"希望不会太久。"},
/* --- 日常高频动词 --- */
{w:"get",p:"/ɡet/",t:"v.",z:"得到；变得；明白（万能动词）",e:"I didn't get what she meant.",ez:"我没明白她什么意思。"},
{w:"grab",p:"/ɡræb/",t:"v.",z:"抓；赶紧买/吃点东西",e:"Let's grab a coffee.",ez:"我们去喝杯咖啡吧。"},
{w:"figure",p:"/ˈfɪɡjər/",t:"v./n.",z:"弄明白；认为",e:"I can't figure out how it works.",ez:"我搞不懂这怎么用。"},
{w:"handle",p:"/ˈhændl/",t:"v.",z:"处理，应付",e:"I'll handle it.",ez:"我来处理。"},
{w:"deal",p:"/diːl/",t:"v./n.",z:"处理（deal with）；交易",e:"That's a great deal.",ez:"这买卖太划算了。"},
{w:"stick",p:"/stɪk/",t:"v.",z:"粘；坚持（stick to/with）",e:"Just stick with me.",ez:"跟着我就行。"},
{w:"hang",p:"/hæŋ/",t:"v.",z:"挂；闲逛（hang out）",e:"Wanna hang out tonight?",ez:"今晚要不要一起玩？"},
{w:"check",p:"/tʃek/",t:"v./n.",z:"查看；检查；买单",e:"Let me check my schedule.",ez:"我看下日程。"},
{w:"fix",p:"/fɪks/",t:"v.",z:"修；准备（吃的）",e:"I'll fix us some dinner.",ez:"我给咱们弄点晚饭。"},
{w:"run",p:"/rʌn/",t:"v.",z:"跑；经营；开（车）",e:"I need to run some errands.",ez:"我得去办点杂事。"},
{w:"catch",p:"/kætʃ/",t:"v.",z:"抓住；赶上（车）；听清",e:"I didn't catch that. Can you repeat?",ez:"我没听清，能重复一下吗？"},
{w:"miss",p:"/mɪs/",t:"v.",z:"想念；错过",e:"I missed the bus.",ez:"我错过了公交。"},
{w:"afford",p:"/əˈfɔːrd/",t:"v.",z:"负担得起",e:"I can't afford that right now.",ez:"我现在买不起。"},
{w:"bother",p:"/ˈbɑːðər/",t:"v.",z:"打扰；费心",e:"Sorry to bother you.",ez:"抱歉打扰一下。"},
{w:"mind",p:"/maɪnd/",t:"v./n.",z:"介意；头脑",e:"Do you mind if I sit here?",ez:"介意我坐这吗？"},
{w:"care",p:"/ker/",t:"v./n.",z:"在乎；照顾（care about/for）",e:"I don't care either way.",ez:"我哪种都无所谓。"},
{w:"realize",p:"/ˈriːəlaɪz/",t:"v.",z:"意识到",e:"I didn't realize it was so late.",ez:"我没意识到已经这么晚了。"},
{w:"guess",p:"/ɡes/",t:"v.",z:"猜；觉得（I guess=我想）",e:"I guess you're right.",ez:"我想你是对的。"},
{w:"wonder",p:"/ˈwʌndər/",t:"v.",z:"想知道；好奇",e:"I wonder if he'll show up.",ez:"我好奇他会不会来。"},
{w:"pretend",p:"/prɪˈtend/",t:"v.",z:"假装",e:"Don't pretend you don't know.",ez:"别装不知道。"},
{w:"manage",p:"/ˈmænɪdʒ/",t:"v.",z:"设法做到；管理",e:"Somehow I managed to finish it.",ez:"我总算设法做完了。"},
{w:"avoid",p:"/əˈvɔɪd/",t:"v.",z:"避免",e:"I'm trying to avoid traffic.",ez:"我在尽量避开堵车。"},
{w:"finish",p:"/ˈfɪnɪʃ/",t:"v.",z:"完成",e:"I'm almost finished.",ez:"我快做完了。"},
{w:"waste",p:"/weɪst/",t:"v./n.",z:"浪费",e:"Don't waste your time.",ez:"别浪费时间。"},
{w:"save",p:"/seɪv/",t:"v.",z:"节省；救；保存",e:"That'll save us a lot of time.",ez:"那能给我们省很多时间。"},
{w:"borrow",p:"/ˈbɑːroʊ/",t:"v.",z:"借入",e:"Can I borrow your charger?",ez:"能借下你充电器吗？"},
{w:"lend",p:"/lend/",t:"v.",z:"借出",e:"I'll lend you twenty bucks.",ez:"我借你二十块。"},
{w:"owe",p:"/oʊ/",t:"v.",z:"欠",e:"I owe you one.",ez:"我欠你个人情。"},
{w:"remind",p:"/rɪˈmaɪnd/",t:"v.",z:"提醒；使想起",e:"Remind me to call her back.",ez:"提醒我给她回电话。"},
{w:"explain",p:"/ɪkˈspleɪn/",t:"v.",z:"解释",e:"Let me explain.",ez:"让我解释一下。"},
{w:"suggest",p:"/səɡˈdʒest/",t:"v.",z:"建议",e:"I suggest we leave now.",ez:"我建议现在就走。"},
{w:"recommend",p:"/ˌrekəˈmend/",t:"v.",z:"推荐",e:"Can you recommend a good place?",ez:"能推荐个好地方吗？"},
{w:"confirm",p:"/kənˈfɜːrm/",t:"v.",z:"确认",e:"I'd like to confirm my appointment.",ez:"我想确认下我的预约。"},
{w:"cancel",p:"/ˈkænsl/",t:"v.",z:"取消",e:"I had to cancel the meeting.",ez:"我不得不取消会议。"},
{w:"reschedule",p:"/riːˈskedʒuːl/",t:"v.",z:"改期",e:"Can we reschedule for Friday?",ez:"能改到周五吗？"},
{w:"deliver",p:"/dɪˈlɪvər/",t:"v.",z:"递送",e:"It'll be delivered tomorrow.",ez:"明天会送到。"},
{w:"return",p:"/rɪˈtɜːrn/",t:"v./n.",z:"归还；返回",e:"I need to return this shirt.",ez:"我得把这件衬衫退了。"},
{w:"refund",p:"/ˈriːfʌnd/",t:"v./n.",z:"退款",e:"Can I get a refund?",ez:"能退款吗？"},
{w:"order",p:"/ˈɔːrdər/",t:"v./n.",z:"点（餐）；订单",e:"Are you ready to order?",ez:"您准备好点餐了吗？"},
{w:"book",p:"/bʊk/",t:"v./n.",z:"预订；书",e:"I booked a table for two.",ez:"我订了两个人的位子。"},
{w:"pack",p:"/pæk/",t:"v.",z:"打包，收拾行李",e:"I haven't packed yet.",ez:"我还没收拾行李。"},
{w:"move",p:"/muːv/",t:"v.",z:"移动；搬家",e:"I'm moving next month.",ez:"我下个月搬家。"},
{w:"settle",p:"/ˈsetl/",t:"v.",z:"安顿；解决",e:"It took a while to settle in.",ez:"适应花了一阵子。"},
{w:"show up",p:"/ʃoʊ ʌp/",t:"phr.",z:"出现，到场",e:"He never showed up.",ez:"他根本没来。"},
{w:"end up",p:"/end ʌp/",t:"phr.",z:"最终成为/做了",e:"We ended up staying home.",ez:"我们最后待在了家。"},
{w:"figure out",p:"/ˈfɪɡjər aʊt/",t:"phr.",z:"搞明白，弄懂",e:"I finally figured it out.",ez:"我终于搞明白了。"},
{w:"work out",p:"/wɜːrk aʊt/",t:"phr.",z:"锻炼；解决；顺利进行",e:"Everything worked out fine.",ez:"一切都很顺利。"},
{w:"come up",p:"/kʌm ʌp/",t:"phr.",z:"发生；被提到",e:"Something came up.",ez:"出了点事。"},
{w:"run out of",p:"/rʌn aʊt əv/",t:"phr.",z:"用完",e:"We're running out of milk.",ez:"我们牛奶快没了。"},
{w:"look forward to",p:"/lʊk ˈfɔːrwərd tuː/",t:"phr.",z:"期待",e:"I look forward to hearing from you.",ez:"期待您的回复。"},
{w:"take care of",p:"/teɪk ker əv/",t:"phr.",z:"处理；照顾",e:"I'll take care of it.",ez:"这事儿我来处理。"},
{w:"get along with",p:"/ɡet əˈlɔːŋ wɪð/",t:"phr.",z:"与…相处",e:"I get along with my roommate.",ez:"我和室友相处得不错。"},
/* --- 时间与频率 --- */
{w:"schedule",p:"/ˈskedʒuːl/",t:"n./v.",z:"日程；安排",e:"My schedule is pretty tight.",ez:"我日程挺紧的。"},
{w:"deadline",p:"/ˈdedlaɪn/",t:"n.",z:"截止日期",e:"The deadline is Friday.",ez:"截止日期是周五。"},
{w:"appointment",p:"/əˈpɔɪntmənt/",t:"n.",z:"预约，约见",e:"I have a doctor's appointment.",ez:"我约了医生。"},
{w:"available",p:"/əˈveɪləbl/",t:"adj.",z:"有空的；可获得的",e:"Are you available this afternoon?",ez:"你下午有空吗？"},
{w:"convenient",p:"/kənˈviːniənt/",t:"adj.",z:"方便的",e:"Is that convenient for you?",ez:"这对你方便吗？"},
{w:"rush",p:"/rʌʃ/",t:"v./n.",z:"赶时间；匆忙",e:"I'm in a rush right now.",ez:"我现在很赶。"},
{w:"delay",p:"/dɪˈleɪ/",t:"v./n.",z:"延误",e:"The flight was delayed two hours.",ez:"航班延误了两小时。"},
{w:"recently",p:"/ˈriːsntli/",t:"adv.",z:"最近",e:"I've been really busy recently.",ez:"我最近特别忙。"},
{w:"lately",p:"/ˈleɪtli/",t:"adv.",z:"近来",e:"I haven't seen him lately.",ez:"我最近没见过他。"},
{w:"eventually",p:"/ɪˈventʃuəli/",t:"adv.",z:"最终",e:"We'll get there eventually.",ez:"我们最终会到的。"},
{w:"immediately",p:"/ɪˈmiːdiətli/",t:"adv.",z:"立刻",e:"I'll do it immediately.",ez:"我马上去做。"},
{w:"afterwards",p:"/ˈæftərwərdz/",t:"adv.",z:"之后",e:"We can grab a drink afterwards.",ez:"之后我们可以去喝一杯。"},
{w:"meanwhile",p:"/ˈmiːnwaɪl/",t:"adv.",z:"与此同时",e:"Meanwhile, I'll start the report.",ez:"同时我来开始写报告。"},
{w:"occasionally",p:"/əˈkeɪʒənəli/",t:"adv.",z:"偶尔",e:"I go there occasionally.",ez:"我偶尔去那儿。"},
{w:"constantly",p:"/ˈkɑːnstəntli/",t:"adv.",z:"不断地",e:"He's constantly checking his phone.",ez:"他不停地看手机。"},
{w:"asap",p:"/ˌeɪ es eɪ ˈpiː/",t:"adv.",z:"尽快（as soon as possible）",e:"I need that report ASAP.",ez:"那份报告我急着要。"},
/* --- 描述人与物 --- */
{w:"guy",p:"/ɡaɪ/",t:"n.",z:"家伙，哥们（口语极常用）",e:"He's a nice guy.",ez:"他人挺好的。"},
{w:"stuff",p:"/stʌf/",t:"n.",z:"东西，玩意儿（不可数）",e:"I left my stuff at your place.",ez:"我把东西落你那儿了。"},
{w:"thing",p:"/θɪŋ/",t:"n.",z:"东西；事情",e:"One more thing before you go.",ez:"你走之前还有一件事。"},
{w:"weird",p:"/wɪrd/",t:"adj.",z:"奇怪的",e:"That's weird.",ez:"真奇怪。"},
{w:"odd",p:"/ɑːd/",t:"adj.",z:"怪的；奇数的",e:"There's something odd about him.",ez:"他有点怪怪的。"},
{w:"awesome",p:"/ˈɔːsəm/",t:"adj.",z:"太棒了（美语高频赞美）",e:"That's awesome!",ez:"太赞了！"},
{w:"cool",p:"/kuːl/",t:"adj.",z:"酷的；没问题",e:"Cool with me.",ez:"我没问题。"},
{w:"nice",p:"/naɪs/",t:"adj.",z:"好的；友善的",e:"That's nice of you.",ez:"你真好。"},
{w:"decent",p:"/ˈdiːsnt/",t:"adj.",z:"还不错的，像样的",e:"It's a decent place to eat.",ez:"这地方吃饭还不错。"},
{w:"terrible",p:"/ˈterəbl/",t:"adj.",z:"糟透了",e:"The service was terrible.",ez:"服务糟透了。"},
{w:"annoying",p:"/əˈnɔɪɪŋ/",t:"adj.",z:"烦人的",e:"That noise is so annoying.",ez:"那噪音真烦人。"},
{w:"confusing",p:"/kənˈfjuːzɪŋ/",t:"adj.",z:"令人困惑的",e:"The instructions are confusing.",ez:"说明写得很让人困惑。"},
{w:"reliable",p:"/rɪˈlaɪəbl/",t:"adj.",z:"可靠的",e:"He's very reliable.",ez:"他很靠谱。"},
{w:"flexible",p:"/ˈfleksəbl/",t:"adj.",z:"灵活的",e:"I'm flexible on the time.",ez:"时间上我很灵活。"},
{w:"crowded",p:"/ˈkraʊdɪd/",t:"adj.",z:"拥挤的",e:"The train was crowded.",ez:"地铁很挤。"},
{w:"expensive",p:"/ɪkˈspensɪv/",t:"adj.",z:"昂贵的",e:"It's a bit expensive.",ez:"有点贵。"},
{w:"affordable",p:"/əˈfɔːrdəbl/",t:"adj.",z:"负担得起的",e:"It's pretty affordable.",ez:"这挺便宜的。"},
{w:"huge",p:"/hjuːdʒ/",t:"adj.",z:"巨大的",e:"That's a huge difference.",ez:"那差别可太大了。"},
{w:"tiny",p:"/ˈtaɪni/",t:"adj.",z:"极小的",e:"My apartment is tiny.",ez:"我的公寓特别小。"},
{w:"brand new",p:"/brænd nuː/",t:"adj.",z:"全新的",e:"I just got a brand new laptop.",ez:"我刚买了台全新的笔记本。"},
{w:"used to",p:"/juːst tuː/",t:"phr.",z:"过去常常",e:"I used to live in Boston.",ez:"我以前住在波士顿。"},
{w:"kind of",p:"/kaɪnd əv/",t:"phr.",z:"有点儿（kinda）",e:"I'm kind of tired.",ez:"我有点累。"},
{w:"a lot of",p:"/ə lɑːt əv/",t:"phr.",z:"很多",e:"There's a lot of traffic today.",ez:"今天堵得厉害。"},
{w:"no big deal",p:"/noʊ bɪɡ diːl/",t:"phr.",z:"没什么大不了",e:"Don't worry, no big deal.",ez:"别担心，没什么大不了。"},
/* --- 情绪与状态 --- */
{w:"exhausted",p:"/ɪɡˈzɔːstɪd/",t:"adj.",z:"精疲力尽的",e:"I'm completely exhausted.",ez:"我彻底累瘫了。"},
{w:"stressed",p:"/strest/",t:"adj.",z:"压力大的",e:"I've been really stressed lately.",ez:"我最近压力特别大。"},
{w:"upset",p:"/ʌpˈset/",t:"adj./v.",z:"难过；生气",e:"She was upset about the news.",ez:"她为这个消息很难过。"},
{w:"relieved",p:"/rɪˈliːvd/",t:"adj.",z:"松了口气的",e:"I'm so relieved it's over.",ez:"总算结束了，我如释重负。"},
{w:"grateful",p:"/ˈɡreɪtfl/",t:"adj.",z:"感激的",e:"I'm really grateful for your help.",ez:"非常感谢你的帮助。"},
{w:"embarrassed",p:"/ɪmˈbærəst/",t:"adj.",z:"尴尬的",e:"I felt so embarrassed.",ez:"我觉得特别尴尬。"},
{w:"confused",p:"/kənˈfjuːzd/",t:"adj.",z:"困惑的",e:"Sorry, I'm a little confused.",ez:"抱歉，我有点糊涂了。"},
{w:"nervous",p:"/ˈnɜːrvəs/",t:"adj.",z:"紧张的",e:"I'm nervous about the interview.",ez:"我对面试很紧张。"},
{w:"excited",p:"/ɪkˈsaɪtɪd/",t:"adj.",z:"兴奋的",e:"I'm so excited for you!",ez:"我真为你高兴！"},
{w:"disappointed",p:"/ˌdɪsəˈpɔɪntɪd/",t:"adj.",z:"失望的",e:"I was a bit disappointed.",ez:"我有点失望。"},
{w:"frustrated",p:"/ˈfrʌstreɪtɪd/",t:"adj.",z:"受挫的，郁闷的",e:"I'm getting frustrated with this.",ez:"我对这事越来越烦。"},
{w:"mood",p:"/muːd/",t:"n.",z:"心情",e:"I'm not in the mood.",ez:"我没那个心情。"},
{w:"rough",p:"/rʌf/",t:"adj.",z:"艰难的；粗糙的",e:"I had a rough day.",ez:"我今天过得很糟。"},
{w:"chill",p:"/tʃɪl/",t:"adj./v.",z:"放松的；闲着",e:"Let's just chill at home.",ez:"咱就在家待着放松吧。"},
{w:"beat",p:"/biːt/",t:"adj./v.",z:"累坏了；打败",e:"I'm beat. Let's call it a night.",ez:"我累坏了，今晚到此为止吧。"},
/* --- 生活场景：饮食 --- */
{w:"grocery",p:"/ˈɡroʊsəri/",t:"n.",z:"食品杂货（groceries）",e:"I need to buy some groceries.",ez:"我得买点吃的。"},
{w:"snack",p:"/snæk/",t:"n./v.",z:"零食；吃点心",e:"Want a snack?",ez:"来点零食吗？"},
{w:"leftovers",p:"/ˈleftoʊvərz/",t:"n.",z:"剩饭菜",e:"We're having leftovers tonight.",ez:"我们今晚吃剩的。"},
{w:"takeout",p:"/ˈteɪkaʊt/",t:"n.",z:"外卖（=takeaway）",e:"Let's get takeout tonight.",ez:"今晚叫外卖吧。"},
{w:"menu",p:"/ˈmenjuː/",t:"n.",z:"菜单",e:"Can I see the menu, please?",ez:"麻烦给我看下菜单。"},
{w:"appetizer",p:"/ˈæpɪtaɪzər/",t:"n.",z:"开胃菜",e:"We'll start with an appetizer.",ez:"我们先来个开胃菜。"},
{w:"bill",p:"/bɪl/",t:"n.",z:"账单",e:"Can we get the bill, please?",ez:"麻烦买单。"},
{w:"tip",p:"/tɪp/",t:"n./v.",z:"小费；建议",e:"Should we leave a tip?",ez:"我们要留小费吗？"},
{w:"refill",p:"/ˈriːfɪl/",t:"n./v.",z:"续杯",e:"Can I get a refill, please?",ez:"麻烦续一杯。"},
{w:"to-go",p:"/tə ɡoʊ/",t:"adj.",z:"外带的",e:"I'll have it to go.",ez:"我要外带。"},
{w:"diet",p:"/ˈdaɪət/",t:"n.",z:"饮食；节食",e:"I'm on a diet.",ez:"我在节食。"},
{w:"ingredient",p:"/ɪnˈɡriːdiənt/",t:"n.",z:"食材，成分",e:"What are the ingredients?",ez:"都有什么配料？"},
{w:"microwave",p:"/ˈmaɪkrəweɪv/",t:"n./v.",z:"微波炉；微波加热",e:"Just microwave it for two minutes.",ez:"微波两分钟就行。"},
{w:"dishwasher",p:"/ˈdɪʃwɔːʃər/",t:"n.",z:"洗碗机",e:"Just put it in the dishwasher.",ez:"放进洗碗机就行。"},
/* --- 生活场景：出行 --- */
{w:"commute",p:"/kəˈmjuːt/",t:"n./v.",z:"通勤",e:"My commute is about 40 minutes.",ez:"我通勤大概四十分钟。"},
{w:"traffic",p:"/ˈtræfɪk/",t:"n.",z:"交通；堵车",e:"Traffic was brutal this morning.",ez:"今早堵得要命。"},
{w:"subway",p:"/ˈsʌbweɪ/",t:"n.",z:"地铁（纽约等说法）",e:"I take the subway to work.",ez:"我坐地铁上班。"},
{w:"gas station",p:"/ɡæs ˈsteɪʃn/",t:"n.",z:"加油站",e:"There's a gas station up ahead.",ez:"前面有个加油站。"},
{w:"parking",p:"/ˈpɑːrkɪŋ/",t:"n.",z:"停车",e:"Parking is a nightmare here.",ez:"这儿停车简直是噩梦。"},
{w:"flight",p:"/flaɪt/",t:"n.",z:"航班",e:"My flight got canceled.",ez:"我的航班取消了。"},
{w:"gate",p:"/ɡeɪt/",t:"n.",z:"登机口；大门",e:"We board at gate B12.",ez:"我们在 B12 登机口登机。"},
{w:"luggage",p:"/ˈlʌɡɪdʒ/",t:"n.",z:"行李",e:"My luggage got lost.",ez:"我的行李丢了。"},
{w:"boarding pass",p:"/ˈbɔːrdɪŋ pæs/",t:"n.",z:"登机牌",e:"May I see your boarding pass?",ez:"能看下您的登机牌吗？"},
{w:"window seat",p:"/ˈwɪndoʊ siːt/",t:"n.",z:"靠窗座位",e:"I'd prefer a window seat.",ez:"我想要靠窗的座位。"},
{w:"transfer",p:"/trænsˈfɜːr/",t:"v./n.",z:"换乘；转账",e:"Do I need to transfer?",ez:"我需要换乘吗？"},
{w:"get off",p:"/ɡet ɔːf/",t:"phr.",z:"下车",e:"I get off at the next stop.",ez:"我下一站下车。"},
{w:"pick up",p:"/pɪk ʌp/",t:"phr.",z:"接（人）；取（物）",e:"Can you pick me up at eight?",ez:"你八点能来接我吗？"},
{w:"drop off",p:"/drɑːp ɔːf/",t:"phr.",z:"顺路放下；送达",e:"I'll drop you off at the station.",ez:"我顺路把你送到车站。"},
/* --- 生活场景：工作与钱 --- */
{w:"boss",p:"/bɔːs/",t:"n.",z:"老板",e:"My boss is in a meeting.",ez:"我老板在开会。"},
{w:"coworker",p:"/ˈkoʊwɜːrkər/",t:"n.",z:"同事",e:"I'm grabbing lunch with coworkers.",ez:"我和同事去吃午饭。"},
{w:"shift",p:"/ʃɪft/",t:"n.",z:"班次",e:"I'm on the night shift.",ez:"我上夜班。"},
{w:"overtime",p:"/ˈoʊvərtaɪm/",t:"n.",z:"加班",e:"I worked overtime last week.",ez:"我上周加班了。"},
{w:"raise",p:"/reɪz/",t:"n./v.",z:"加薪；提高",e:"I asked for a raise.",ez:"我要求加薪了。"},
{w:"budget",p:"/ˈbʌdʒɪt/",t:"n.",z:"预算",e:"That's over my budget.",ez:"那超出我预算了。"},
{w:"on sale",p:"/ɑːn seɪl/",t:"phr.",z:"打折",e:"Is this on sale?",ez:"这个在打折吗？"},
{w:"discount",p:"/ˈdɪskaʊnt/",t:"n.",z:"折扣",e:"Do you have any discounts?",ez:"有折扣吗？"},
{w:"receipt",p:"/rɪˈsiːt/",t:"n.",z:"收据（p不发音）",e:"Keep your receipt.",ez:"把收据留好。"},
{w:"charge",p:"/tʃɑːrdʒ/",t:"v./n.",z:"收费；充电",e:"They charged me twice.",ez:"他们收了我两次钱。"},
{w:"split the bill",p:"/splɪt ðə bɪl/",t:"phr.",z:"AA 制，平摊",e:"Let's split the bill.",ez:"咱们 AA 吧。"},
{w:"paycheck",p:"/ˈpeɪtʃek/",t:"n.",z:"工资支票/薪水",e:"My paycheck hasn't come in.",ez:"我工资还没到账。"},
{w:"insurance",p:"/ɪnˈʃʊrəns/",t:"n.",z:"保险",e:"Does that include insurance?",ez:"含保险吗？"},
{w:"deposit",p:"/dɪˈpɑːzɪt/",t:"n./v.",z:"押金；存款",e:"We need a security deposit.",ez:"我们需要交押金。"},
/* --- 生活场景：社交与沟通 --- */
{w:"catch up",p:"/kætʃ ʌp/",t:"phr.",z:"叙旧；赶上进度",e:"Let's catch up next week.",ez:"下周我们叙叙旧。"},
{w:"no worries",p:"/noʊ ˈwɜːriz/",t:"phr.",z:"没事儿，别客气",e:"Thanks! — No worries.",ez:"谢谢！——不客气。"},
{w:"my bad",p:"/maɪ bæd/",t:"phr.",z:"我的错",e:"Oh, my bad. I thought it was yours.",ez:"哦，我的错，我以为是你的。"},
{w:"long story",p:"/lɔːŋ ˈstɔːri/",t:"phr.",z:"说来话长",e:"It's a long story.",ez:"说来话长。"},
{w:"fair enough",p:"/fer ɪˈnʌf/",t:"phr.",z:"有道理，说得对",e:"Fair enough, let's do it your way.",ez:"有道理，那就按你的来。"},
{w:"make sense",p:"/meɪk sens/",t:"phr.",z:"说得通",e:"Does that make sense?",ez:"这说得通吗？"},
{w:"point is",p:"/pɔɪnt ɪz/",t:"phr.",z:"重点是",e:"The point is, we need more time.",ez:"重点是我们得有更多时间。"},
{w:"by the way",p:"/baɪ ðə weɪ/",t:"phr.",z:"顺便说一下",e:"By the way, did you call him?",ez:"顺便问一句，你给他打电话了吗？"},
{w:"speaking of",p:"/ˈspiːkɪŋ əv/",t:"phr.",z:"说到…（顺接话题）",e:"Speaking of food, I'm starving.",ez:"说到吃的，我饿死了。"},
{w:"to be fair",p:"/tuː biː fer/",t:"phr.",z:"说句公道话",e:"To be fair, he did try.",ez:"说句公道话，他确实试了。"},
/* --- 健康与天气 --- */
{w:"appointment card",p:"/əˈpɔɪntmənt kɑːrd/",t:"n.",z:"预约单",e:"Don't lose your appointment card.",ez:"别把预约单弄丢了。"},
{w:"symptom",p:"/ˈsɪmptəm/",t:"n.",z:"症状",e:"What are your symptoms?",ez:"您有什么症状？"},
{w:"prescription",p:"/prɪˈskrɪpʃn/",t:"n.",z:"处方",e:"I need to fill a prescription.",ez:"我要去拿处方药。"},
{w:"pharmacy",p:"/ˈfɑːrməsi/",t:"n.",z:"药房",e:"The pharmacy closes at nine.",ez:"药房九点关门。"},
{w:"sore throat",p:"/sɔːr θroʊt/",t:"n.",z:"嗓子疼",e:"I have a sore throat.",ez:"我嗓子疼。"},
{w:"fever",p:"/ˈfiːvər/",t:"n.",z:"发烧",e:"Do you have a fever?",ez:"你发烧吗？"},
{w:"allergy",p:"/ˈælərdʒi/",t:"n.",z:"过敏",e:"I have a nut allergy.",ez:"我对坚果过敏。"},
{w:"insurance card",p:"/ɪnˈʃʊrəns kɑːrd/",t:"n.",z:"医保卡",e:"Please show your insurance card.",ez:"请出示您的医保卡。"},
{w:"chilly",p:"/ˈtʃɪli/",t:"adj.",z:"有点冷的",e:"It's a bit chilly today.",ez:"今天有点凉。"},
{w:"humid",p:"/ˈhjuːmɪd/",t:"adj.",z:"潮湿闷热的",e:"It gets really humid in summer.",ez:"夏天这里特别潮。"},
{w:"forecast",p:"/ˈfɔːrkæst/",t:"n.",z:"天气预报",e:"The forecast says rain.",ez:"预报说有雨。"},
{w:"freezing",p:"/ˈfriːzɪŋ/",t:"adj.",z:"冻死了",e:"It's freezing in here!",ez:"这里冷死了！"}
];
