/* 连读实验室语料：书面语 vs 美国人实际说出来的样子
   cat=类型 w=书面写法 h=实际听到的写法(近似拼写) ipa=实际读音 z=中文 n=要点 */
window.LINKING = [
/* ===== A. 缩读 contraction ===== */
{cat:"contract",w:"I'm going to tell him.",h:"I'm gonna tell 'im.",ipa:"/aɪm ˈɡʌnə tel ɪm/",z:"我要告诉他。",n:"going to → gonna；him 弱读成 'im"},
{cat:"contract",w:"Do you want to come?",h:"Dyawanna come?",ipa:"/dʒəˈwɑnə kʌm/",z:"你想来吗？",n:"Do you → d'ya/dʒə；want to → wanna"},
{cat:"contract",w:"I have got to go now.",h:"I gotta go now.",ipa:"/aɪ ˈɡɑtə ɡoʊ naʊ/",z:"我现在得走了。",n:"have got to → gotta"},
{cat:"contract",w:"It is kind of cold.",h:"It's kinda cold.",ipa:"/ɪts ˈkaɪndə koʊld/",z:"有点冷。",n:"kind of → kinda"},
{cat:"contract",w:"It is sort of strange.",h:"It's sorta strange.",ipa:"/ɪts ˈsɔrtə streɪndʒ/",z:"有点奇怪。",n:"sort of → sorta"},
{cat:"contract",w:"I am out of here.",h:"I'm outta here.",ipa:"/aɪm ˈaʊtə hɪr/",z:"我走了。",n:"out of → outta"},
{cat:"contract",w:"Let me see that.",h:"Lemme see that.",ipa:"/ˈlemi si ðæt/",z:"让我看看那个。",n:"let me → lemme"},
{cat:"contract",w:"Give me a second.",h:"Gimme a sec.",ipa:"/ˈɡɪmi ə sek/",z:"给我一秒钟。",n:"give me → gimme"},
{cat:"contract",w:"Don't you think so?",h:"Doncha think so?",ipa:"/ˈdoʊntʃə θɪŋk soʊ/",z:"你不这么认为吗？",n:"don't you → doncha"},
{cat:"contract",w:"Did you eat yet?",h:"Didja eat yet?",ipa:"/ˈdɪdʒə it jɛt/",z:"你吃了吗？",n:"did you → didja（d+y 同化为 /dʒ/）"},
{cat:"contract",w:"What are you doing?",h:"Whatcha doin'?",ipa:"/ˈwʌtʃə ˈduɪn/",z:"你在干嘛？",n:"what are you → whatcha；-ing 常读成 -in'"},
{cat:"contract",w:"What do you mean?",h:"Whaddaya mean?",ipa:"/ˈwʌdəjə min/",z:"你什么意思？",n:"what do you → whaddaya"},
{cat:"contract",w:"I don't know.",h:"I dunno.",ipa:"/aɪ dəˈnoʊ/",z:"我不知道。",n:"don't know → dunno"},
{cat:"contract",w:"Because it's late.",h:"'Cause it's late.",ipa:"/kəz ɪts leɪt/",z:"因为太晚了。",n:"because → 'cause / cuz"},
{cat:"contract",w:"It isn't my problem.",h:"It ain't my problem.",ipa:"/ɪt eɪnt maɪ ˈprɑbləm/",z:"那不是我的问题。",n:"isn't → ain't（非正式）"},
{cat:"contract",w:"Are you all ready?",h:"Are y'all ready?",ipa:"/ər jɔl ˈredi/",z:"你们准备好了吗？",n:"you all → y'all"},
{cat:"contract",w:"I'm going to ask them.",h:"I'ma ask 'em.",ipa:"/ˈaɪmə æsk əm/",z:"我要去问他们。",n:"I'm going to → I'ma；them → 'em"},
{cat:"contract",w:"Should have told me.",h:"Shoulda told me.",ipa:"/ˈʃʊdə toʊld mi/",z:"你早该告诉我。",n:"should have → shoulda（have → /ə/）"},
{cat:"contract",w:"Could have been worse.",h:"Coulda been worse.",ipa:"/ˈkʊdə bɪn wɜrs/",z:"本来可能更糟。",n:"could have → coulda"},
{cat:"contract",w:"Would have helped you.",h:"Woulda helped ya.",ipa:"/ˈwʊdə helpt jə/",z:"我本会帮你的。",n:"would have → woulda；you → ya"},
{cat:"contract",w:"Must have been them.",h:"Must've been 'em.",ipa:"/ˈmʌstəv bɪn əm/",z:"一定是他们。",n:"must have → must've"},
{cat:"contract",w:"Let us go home.",h:"Let's go home.",ipa:"/lets ɡoʊ hoʊm/",z:"我们回家吧。",n:"let us → let's"},
{cat:"contract",w:"I want to be able to swim.",h:"I wanna be able ta swim.",ipa:"/aɪ ˈwɑnə bi ˈeɪbl tə swɪm/",z:"我希望能会游泳。",n:"to 弱读成 /tə/"},
{cat:"contract",w:"He has got a car.",h:"He's gotta car.",ipa:"/hiz ˈɡɑtə kɑr/",z:"他有辆车。",n:"has got → gotta（口语）"},
{cat:"contract",w:"What is the matter?",h:"What's the matter?",ipa:"/wʌts ðə ˈmædər/",z:"怎么了？",n:"matter 的 tt 浊化成 d：madder"},
{cat:"contract",w:"Come on, let's go.",h:"C'mon, less go.",ipa:"/kəˈmɑn les ɡoʊ/",z:"拜托，走吧。",n:"come on → c'mon；let's → less"},
{cat:"contract",w:"I don't want to.",h:"I don't wanna.",ipa:"/aɪ doʊnt ˈwɑnə/",z:"我不想。",n:"want to → wanna"},
{cat:"contract",w:"There is a lot of time.",h:"There's a lotta time.",ipa:"/ðerz ə ˈlɑtə taɪm/",z:"还有很多时间。",n:"lot of → lotta"},
{cat:"contract",w:"I used to live there.",h:"I useta live there.",ipa:"/aɪ ˈjuːstə lɪv ðer/",z:"我以前住那儿。",n:"used to → useta（注意：否定 didn't use to）"},
{cat:"contract",w:"Going to be late again.",h:"Gonna be late again.",ipa:"/ˈɡʌnə bi leɪt əˈɡen/",z:"又要迟到了。",n:"gonna 是最高频缩读，务必秒懂"},

/* ===== B. 弱读 reduction ===== */
{cat:"reduce",w:"I'm going to the store.",h:"I'm gonna t'the store.",ipa:"/aɪm ˈɡʌnə tə ðə stɔr/",z:"我要去商店。",n:"to → /tə/；the(辅音前) → /ðə/"},
{cat:"reduce",w:"This is for you.",h:"This is fer you.",ipa:"/ðɪs ɪz fər ju/",z:"这是给你的。",n:"for → /fər/（几乎只剩 f + 弱元音）"},
{cat:"reduce",w:"A cup of coffee.",h:"A cuppa coffee.",ipa:"/ə ˈkʌpə ˈkɔfi/",z:"一杯咖啡。",n:"cup of → cuppa"},
{cat:"reduce",w:"Bread and butter.",h:"Bread 'n butter.",ipa:"/bred ən ˈbʌdər/",z:"黄油面包。",n:"and → /ən/ 甚至只留 /n/；butter 的 tt → d"},
{cat:"reduce",w:"I can do it.",h:"I c'n do it.",ipa:"/aɪ kən du ɪt/",z:"我能做。",n:"can 弱读 /kən/；can't 是 /kænt/，靠元音区分"},
{cat:"reduce",w:"I can't do it.",h:"I can't do it.",ipa:"/aɪ kænt du ɪt/",z:"我做不了。",n:"can't 重读 /kænt/，t 不爆破"},
{cat:"reduce",w:"Look at that!",h:"Look at that!",ipa:"/lʊk ət ðæt/",z:"看那个！",n:"at → /ət/；that 结尾 t 不爆破"},
{cat:"reduce",w:"I think that it's fine.",h:"I think th't it's fine.",ipa:"/aɪ θɪŋk ðət ɪts faɪn/",z:"我觉得这没问题。",n:"that(引导从句) → /ðət/"},
{cat:"reduce",w:"Tell them later.",h:"Tell 'em later.",ipa:"/tel əm ˈleɪdər/",z:"待会儿告诉他们。",n:"them → /əm/ 或 'em"},
{cat:"reduce",w:"Two or three.",h:"Two'r three.",ipa:"/tu ər θri/",z:"两三个。",n:"or → /ər/"},
{cat:"reduce",w:"See you later.",h:"See ya later.",ipa:"/si jə ˈleɪdər/",z:"回头见。",n:"you → /jə/ 或 ya"},
{cat:"reduce",w:"Where is he?",h:"Where's he?",ipa:"/werz i/",z:"他在哪？",n:"is 弱读并缩合；he 弱读 /i/"},
{cat:"reduce",w:"Where did he go?",h:"Where'd 'e go?",ipa:"/werd i ɡoʊ/",z:"他去哪了？",n:"did he → /di/；he 的 h 常不发音"},
{cat:"reduce",w:"I have been there.",h:"I've been there.",ipa:"/aɪv bɪn ðer/",z:"我去过那儿。",n:"have → /əv/ 并缩合成 I've"},
{cat:"reduce",w:"She has already left.",h:"She's already left.",ipa:"/ʃiz ɔlˈredi left/",z:"她已经走了。",n:"has → /əz/"},
{cat:"reduce",w:"We had a good time.",h:"We'd a good time.",ipa:"/wid ə ɡʊd taɪm/",z:"我们玩得很开心。",n:"had → /əd/，甚至只剩 'd"},
{cat:"reduce",w:"He was here.",h:"He wuz here.",ipa:"/hi wəz hɪr/",z:"他在这儿。",n:"was → /wəz/"},
{cat:"reduce",w:"They were late.",h:"They were late.",ipa:"/ðeɪ wər leɪt/",z:"他们迟到了。",n:"were → /wər/"},
{cat:"reduce",w:"It has been done.",h:"It's been done.",ipa:"/ɪts bɪn dʌn/",z:"已经做完了。",n:"been 弱读成 /bɪn/"},
{cat:"reduce",w:"Should I go?",h:"Should I go?",ipa:"/ʃʊd aɪ ɡoʊ/",z:"我该去吗？",n:"should 弱读 /ʃəd/（辅音前）"},
{cat:"reduce",w:"There is a problem.",h:"There's a problem.",ipa:"/ðerz ə ˈprɑbləm/",z:"有个问题。",n:"there's + a 连读成 /ðerzə/"},
{cat:"reduce",w:"As soon as possible.",h:"As soon 's possible.",ipa:"/əz suːn əz ˈpɑsəbl/",z:"尽快。",n:"三个词全弱读，ASAP 口语超高频"},
{cat:"reduce",w:"What time is it?",h:"What time'z it?",ipa:"/wʌt taɪm zɪt/",z:"几点了？",n:"is it → /zɪt/ 连成一团"},
{cat:"reduce",w:"Not at all.",h:"No-ta-tall.",ipa:"/nɑdəˈtɔl/",z:"一点也不。",n:"三个词完全连成一体"},
{cat:"reduce",w:"I'll be back in a minute.",h:"I'll be back inna minute.",ipa:"/aɪl bi bæk ɪnə ˈmɪnɪt/",z:"我马上回来。",n:"in a → inna"},

/* ===== C. 连读 linking ===== */
{cat:"link",w:"Turn off the light.",h:"Turn-off the light.",ipa:"/tɜrˈnɔf ðə laɪt/",z:"把灯关了。",n:"辅音 n + 元音 ɔ 连读：turn off → tur-noff"},
{cat:"link",w:"Check it out.",h:"Che-ki-dout.",ipa:"/tʃeɪkɪˈdaʊt/",z:"看看这个。",n:"k 被两元音夹住，浊化并连读"},
{cat:"link",w:"Pick it up.",h:"Pi-ki-dup.",ipa:"/pɪkɪˈdʌp/",z:"把它捡起来。",n:"k 浊化成 /ɡ/ 的感觉，与后面连读"},
{cat:"link",w:"An apple a day.",h:"A-napple a day.",ipa:"/əˈnæpl ə deɪ/",z:"一天一苹果。",n:"an + apple → a-napple"},
{cat:"link",w:"First of all.",h:"Firs-dovall.",ipa:"/fɜrsdəˈvɔl/",z:"首先。",n:"first of → firs-dov，t 浊化后连读"},
{cat:"link",w:"Not on your life.",h:"No-ton your life.",ipa:"/nɑtɑn jər laɪf/",z:"绝不可能。",n:"t 移到后词元音前"},
{cat:"link",w:"Take it easy.",h:"Tay-kit easy.",ipa:"/teɪkɪˈdiːzi/",z:"放松点。",n:"take it → tay-kit；easy 的 s 浊化"},
{cat:"link",w:"Come on in.",h:"C'mon-nin.",ipa:"/kəˈmɑnɪn/",z:"进来吧。",n:"on + in 连读"},
{cat:"link",w:"Look out for cars.",h:"Look-owt for cars.",ipa:"/lʊˈkaʊt fər kɑrz/",z:"小心车。",n:"k 与 out 连读"},
{cat:"link",w:"I'll think about it.",h:"I'll think-about-it.",ipa:"/aɪl θɪŋkəˈbaʊdɪd/",z:"我会考虑的。",n:"about it → about-it，t 浊化成 d"},
{cat:"link",w:"It's all over now.",h:"It's all-over now.",ipa:"/ɪts ɔˈloʊvər naʊ/",z:"一切都结束了。",n:"all over 连读"},
{cat:"link",w:"He's an American.",h:"He's a-namerican.",ipa:"/hiz əˈmerəkən/",z:"他是美国人。",n:"an + American 连读"},
{cat:"link",w:"Far away from home.",h:"Far-away from home.",ipa:"/fɑrəˈweɪ frəm hoʊm/",z:"远离家乡。",r:1,n:"r + 元音连读（美音 r 一定要读出）"},
{cat:"link",w:"There is a pair of shoes.",h:"There's a pair-a shoes.",ipa:"/ðerz ə per ə ʃuz/",z:"有一双鞋。",n:"pair of → pair-a，r 连读"},
{cat:"link",w:"Put it on the table.",h:"Pu-di-don the table.",ipa:"/pʊdɪˈdɑn ðə ˈteɪbl/",z:"把它放桌上。",n:"t 在两元音间浊化成 d（flap）"},
{cat:"link",w:"Get out of here.",h:"Get-oudda here.",ipa:"/ɡeˈdaʊdə hɪr/",z:"滚出去！",n:"get out of → ge-doudda"},
{cat:"link",w:"A lot of people.",h:"A lotta people.",ipa:"/ə ˈlɑdə ˈpipl/",z:"很多人。",n:"lot of → lotta，t 浊化"},
{cat:"link",w:"Right after that.",h:"Ride-after that.",ipa:"/raɪˈdæftər ðæt/",z:"在那之后。",n:"right 的 t 浊化后与 after 连读"},
{cat:"link",w:"What about you?",h:"Whada-boutcha?",ipa:"/ˈwʌdəˈbaʊtʃə/",z:"你呢？",n:"what about you 三连音，超高频"},
{cat:"link",w:"How about a drink?",h:"How-about-a drink?",ipa:"/haʊəˈbaʊtə drɪŋk/",z:"喝一杯怎么样？",n:"how 'bout a → how-bout-a"},
{cat:"link",w:"I need it now.",h:"I nee-dit now.",ipa:"/aɪ ˈnidɪt naʊ/",z:"我现在就需要。",n:"need it → nee-dit"},
{cat:"link",w:"Made of steel.",h:"Made-a steel.",ipa:"/meɪd ə stil/",z:"钢制的。",n:"made of 连读"},
{cat:"link",w:"Keep an eye on him.",h:"Keep-a-nigh on 'im.",ipa:"/kipəˈnaɪ ɑn ɪm/",z:"盯着他。",n:"an eye → a-nigh 连读"},
{cat:"link",w:"Fill out this form.",h:"Fil-lout this form.",ipa:"/fɪˈlaʊt ðɪs fɔrm/",z:"填一下这张表。",n:"l 与 out 连读"},
{cat:"link",w:"Wrap it up.",h:"Rap-i-dup.",ipa:"/ræpɪˈdʌp/",z:"收尾吧。",n:"p 浊化连读"},
{cat:"link",w:"Give it up for him.",h:"Give-i-dup for 'im.",ipa:"/ɡɪvɪˈdʌp fər ɪm/",z:"为他鼓掌。",n:"give it up 三连"},

/* ===== D. 浊化与失爆 flap & stop ===== */
{cat:"flap",w:"Can I have a bottle of water?",h:"Bottle a wader.",ipa:"/ˈbɑdl ə ˈwɔdər/",z:"能给我瓶水吗？",n:"tt 和 t 都浊化成 d：boddle / wader"},
{cat:"flap",w:"I got it.",h:"I god-dit.",ipa:"/aɪ ˈɡɑdɪt/",z:"我懂了。",n:"got it → god-dit（经典浊化）"},
{cat:"flap",w:"Let me get a better one.",h:"Lemme gedda bedder one.",ipa:"/ˈlemi ɡedə ˈbedər wʌn/",z:"让我拿个更好的。",n:"get a → gedda；better → bedder"},
{cat:"flap",w:"It's a little bit cold.",h:"It's a liddle bit cold.",ipa:"/ɪts ə ˈlɪdl bɪt koʊld/",z:"有点冷。",n:"little → liddle"},
{cat:"flap",w:"That's the matter with him.",h:"That's the madder with 'im.",ipa:"/ðæts ðə ˈmædər wɪð ɪm/",z:"他怎么了。",n:"matter → madder"},
{cat:"flap",w:"I'm pretty sure.",h:"I'm priddy sure.",ipa:"/aɪm ˈprɪdi ʃʊr/",z:"我挺确定的。",n:"pretty → priddy"},
{cat:"flap",w:"Wait a minute.",h:"Way-da minute.",ipa:"/weɪdə ˈmɪnɪt/",z:"等一下。",n:"wait a → way-da"},
{cat:"flap",w:"What's the matter, butter?",h:"Madder? Budder?",ipa:"/ˈmædər ˈbʌdər/",z:"怎么了，黄油？",n:"t→d 让 matter 与 madder 同音"},
{cat:"flap",w:"Chicago is windy.",h:"Chicago is windy.",ipa:"/ʃɪˈkɑɡoʊ ɪz ˈwɪndi/",z:"芝加哥风大。",n:"背景知识：windy city 就是芝加哥"},
{cat:"flap",w:"He's at a party.",h:"He's a-da party.",ipa:"/hiz ədə ˈpɑrdi/",z:"他在派对上。",n:"at a → a-da"},
{cat:"flap",w:"I don't want to wait.",h:"I don't wanna wai'." ,ipa:"/aɪ doʊnt ˈwɑnə weɪ/",z:"我不想等。",n:"want to → wanna；want 的 t 失爆"},
{cat:"flap",w:"Sit down, please.",h:"Si' down, please.",ipa:"/sɪˈdaʊn pliz/",z:"请坐。",n:"sit 的 t 后接辅音，只做口型不爆破"},
{cat:"flap",w:"I can't believe it.",h:"I can' believe it.",ipa:"/aɪ kæn bɪˈlivɪt/",z:"我不敢相信。",n:"can't 的 t 被吞掉，靠 /kæn/ 与 can 区分"},
{cat:"flap",w:"Next day we left.",h:"Nex' day we left.",ipa:"/neks deɪ wi left/",z:"第二天我们走了。",n:"next 的 t 在 d 前完全失爆"},
{cat:"flap",w:"I just got back.",h:"I jus' got back.",ipa:"/aɪ dʒʌs ɡɑt bæk/",z:"我刚回来。",n:"just 的 t 失爆"},
{cat:"flap",w:"He's the best friend.",h:"He's the bes' friend.",ipa:"/hiz ðə bes frend/",z:"他是最好的朋友。",n:"best 的 t 失爆"},
{cat:"flap",w:"I slept badly.",h:"I slep' badly.",ipa:"/aɪ slep ˈbædli/",z:"我睡得不好。",n:"slept 的 t 失爆"},
{cat:"flap",w:"Keep talking.",h:"Kee' talking.",ipa:"/ki ˈtɔkɪn/",z:"继续说。",n:"keep 的 p 失爆"},
{cat:"flap",w:"I'd like a hot dog.",h:"I'd like a ha' dog.",ipa:"/aɪd laɪk ə hɑ dɔɡ/",z:"我要个热狗。",n:"hot 的 t 失爆"},
{cat:"flap",w:"That's the right thing.",h:"That's the righ' thing.",ipa:"/ðæts ðə raɪ θɪŋ/",z:"那才是对的。",n:"right 的 t 失爆"},

/* ===== E. 同化 assimilation ===== */
{cat:"assim",w:"Did you see it?",h:"Di-joo see it?",ipa:"/ˈdɪdʒu si ɪt/",z:"你看到了吗？",n:"d + y → /dʒ/（did you → di-joo）"},
{cat:"assim",w:"Would you help me?",h:"Wud-joo help me?",ipa:"/ˈwʊdʒu help mi/",z:"能帮我吗？",n:"would you → wud-joo"},
{cat:"assim",w:"Could you do it?",h:"Cud-joo do it?",ipa:"/ˈkʊdʒu du ɪt/",z:"你能做吗？",n:"could you → cud-joo"},
{cat:"assim",w:"I miss you.",h:"I mi-shoo.",ipa:"/aɪ ˈmɪʃu/",z:"我想你。",n:"s + y → /ʃ/（miss you → mi-shoo）"},
{cat:"assim",w:"Bless you!",h:"Ble-shoo!",ipa:"/ˈbleʃu/",z:"（打喷嚏）保佑你！",n:"s + y → /ʃ/"},
{cat:"assim",w:"Don't you like it?",h:"Don-chew like it?",ipa:"/ˈdoʊntʃu laɪk ɪt/",z:"你不喜欢吗？",n:"t + y → /tʃ/"},
{cat:"assim",w:"Can't you come?",h:"Can-chew come?",ipa:"/ˈkæntʃu kʌm/",z:"你不能来吗？",n:"t + y → /tʃ/"},
{cat:"assim",w:"About you.",h:"Abou-chew.",ipa:"/əˈbaʊtʃu/",z:"关于你。",n:"t + y → /tʃ/"},
{cat:"assim",w:"I'll bet you.",h:"I'll be-chew.",ipa:"/aɪl ˈbetʃu/",z:"我跟你打赌。",n:"bet you → be-chew"},
{cat:"assim",w:"Last year I went.",h:"Las-cheer I went.",ipa:"/læsˈtʃɪr aɪ went/",z:"去年我去了。",n:"t + y → /tʃ/"},
{cat:"assim",w:"In case you need it.",h:"In ca-shoo need it.",ipa:"/ɪn ˈkeɪʃu nid ɪt/",z:"万一你需要。",n:"s + y → /ʃ/"},
{cat:"assim",w:"Those years were hard.",h:"Those years were hard.",ipa:"/ðoʊz jɪrz wər hɑrd/",z:"那些年很艰难。",n:"z + y → /ʒ/（较慢速时保留）"},
{cat:"assim",w:"Help you?",h:"Help you?",ipa:"/help ju/",z:"需要帮忙吗？",n:"p + y 通常不同化，直接连读"},
{cat:"assim",w:"Would you mind?",h:"Wud-joo mind?",ipa:"/ˈwʊdʒu maɪnd/",z:"你介意吗？",n:"would you → wud-joo，高频礼貌用语"},
{cat:"assim",w:"What did you say?",h:"Whadid-ja say?",ipa:"/ˈwʌdɪdʒə seɪ/",z:"你说什么？",n:"did you → di-ja，前面再吞音"},

/* ===== F. 综合高速串读 ===== */
{cat:"fast",w:"What are you going to do about it?",h:"Whatcha gonna do 'bout it?",ipa:"/ˈwʌtʃə ˈɡʌnə du ˈbaʊdɪd/",z:"你打算怎么办？",n:"五连音：whatcha gonna do 'bout it"},
{cat:"fast",w:"I don't know what to do.",h:"I dunno what ta do.",ipa:"/aɪ dəˈnoʊ wʌt tə du/",z:"我不知道该怎么办。",n:"dunno + whadda"},
{cat:"fast",w:"Let me get out of here.",h:"Lemme ged-oudda here.",ipa:"/ˈlemi ɡeˈdaʊdə hɪr/",z:"让我离开这儿。",n:"lemme + gedda + outta"},
{cat:"fast",w:"I've got to go and get it.",h:"I gotta go 'n ge' it.",ipa:"/aɪ ˈɡɑtə ɡoʊ ən ɡedɪd/",z:"我得去拿。",n:"gotta + and + get it"},
{cat:"fast",w:"Did you get a chance to look at it?",h:"Didja gedda chance ta look-a-dit?",ipa:"/ˈdɪdʒə ɡedə tʃæns tə lʊkədɪt/",z:"你有机会看吗？",n:"全句几乎无停顿"},
{cat:"fast",w:"I should have told you earlier.",h:"I shoulda tol-joo earlier.",ipa:"/aɪ ˈʃʊdə ˈtoʊldʒu ˈɜrliər/",z:"我该早点告诉你。",n:"shoulda + told you"},
{cat:"fast",w:"It's kind of hard to say.",h:"It's kinda hard ta say.",ipa:"/ɪts ˈkaɪndə hɑrd tə seɪ/",z:"有点难说。",n:"kinda + hard ta"},
{cat:"fast",w:"What do you want to do?",h:"Whaddaya wanna do?",ipa:"/ˈwʌdəjə ˈwɑnə du/",z:"你想做什么？",n:"whaddaya + wanna"},
{cat:"fast",w:"There isn't anything left.",h:"There isn't anythin' left.",ipa:"/ðer ˈɪzənt ˈeniθɪn left/",z:"什么都没剩。",n:"anything → anythin'（-ing 变 -in'）"},
{cat:"fast",w:"Are you going to be there?",h:"Ya gonna be there?",ipa:"/jə ˈɡʌnə bi ðer/",z:"你会去吗？",n:"are you → ya；gonna"},
{cat:"fast",w:"I want to talk to him about it.",h:"I wanna talk t'him about-it.",ipa:"/aɪ ˈwɑnə tɔk tɪm əˈbaʊdɪd/",z:"我想跟他谈谈这事。",n:"wanna + to him + about it"},
{cat:"fast",w:"He's going to be late again.",h:"He's gonna be late again.",ipa:"/hiz ˈɡʌnə bi leɪt əˈɡen/",z:"他又要迟到了。",n:"He's gonna 连成一串"},
{cat:"fast",w:"How do you know?",h:"How d'ya know?",ipa:"/haʊ dʒə noʊ/",z:"你怎么知道的？",n:"do you → d'ya / dʒə"},
{cat:"fast",w:"Give me a call when you get there.",h:"Gimme a call when ya ge' there.",ipa:"/ˈɡɪmi ə kɔl wen jə ɡeð ðer/",z:"到了给我打电话。",n:"gimme + ya + ge'"},
{cat:"fast",w:"I'm not going to worry about it.",h:"I'm not gonna worry 'bout it.",ipa:"/aɪm nɑt ˈɡʌnə ˈwɜri əˈbaʊdɪd/",z:"我不打算为它担心。",n:"not gonna（注意 not 保留重读）"},
{cat:"fast",w:"What's going on?",h:"What's goin' on?",ipa:"/wʌts ɡoʊɪn ɑn/",z:"发生什么事了？",n:"going → goin'，最高频问候之一"},
{cat:"fast",w:"Come on, we're going to be late.",h:"C'mon, we're gonna be late.",ipa:"/kəˈmɑn wɪr ˈɡʌnə bi leɪt/",z:"快点，我们要迟到了。",n:"c'mon + gonna"},
{cat:"fast",w:"I didn't get a chance to see him.",h:"I didn' gedda chance ta see 'im.",ipa:"/aɪ ˈdɪdən ɡedə tʃæns tə si ɪm/",z:"我没机会见他。",n:"didn't 的 t 吞掉；gedda；'im"},
{cat:"fast",w:"Would you like something to drink?",h:"Wud-joo like somethin' ta drink?",ipa:"/ˈwʊdʒu laɪk ˈsʌmθɪn tə drɪŋk/",z:"要喝点什么吗？",n:"would you → wud-joo；something → somethin'"},
{cat:"fast",w:"That's what I'm talking about.",h:"That's what I'm talkin' about.",ipa:"/ðæts wʌt aɪm ˈtɔkɪn əˈbaʊt/",z:"就是这个意思！",n:"talking → talkin'；about 结尾 t 失爆"},
{cat:"fast",w:"I'll let you know as soon as I can.",h:"I'll letcha know as soon 's I can.",ipa:"/aɪl ˈletʃə noʊ əz suːn z aɪ kæn/",z:"我一有消息就通知你。",n:"let you → letcha；as soon as 全弱读"},
{cat:"fast",w:"Do you mind if I sit here?",h:"D'ya mind if I sit here?",ipa:"/dʒə maɪnd ɪf aɪ sɪt hɪr/",z:"介意我坐这儿吗？",n:"Do you → d'ya"},
{cat:"fast",w:"It’s up to you.",h:"S'up to you.",ipa:"/sʌp tə ju/",z:"你决定。",n:"It's 的 it 几乎消失，只剩 s"},
{cat:"fast",w:"I’ve been meaning to call you.",h:"I've been meanin' ta call ya.",ipa:"/aɪv bɪn ˈminɪn tə kɔl jə/",z:"我一直想给你打电话。",n:"meaning → meanin'；to → ta；you → ya"},
{cat:"fast",w:"Hang on a second, I'll be right back.",h:"Hang on a sec, I'll be right back.",ipa:"/hæŋ ɑn ə sek aɪl bi raɪt bæk/",z:"等一下，我马上回来。",n:"Hang on a sec 是整块固定搭配"}
];
